import type { ToxinEntry, ToxinSource } from "./types";

/**
 * Petwell V1 local toxin reference — the 50 highest-priority toxins for dogs and
 * cats, curated from public veterinary poison-control sources (ASPCA Animal
 * Poison Control and Pet Poison Helpline).
 *
 * Provenance: every entry links to the public source it was transcribed from and
 * is marked `curated_public_source` (NOT yet clinician-verified) with a
 * last-reviewed date. None of these entries contains dosing, antidote, or
 * treatment instructions by design — they describe the hazard and the signs an
 * owner might see, then route to a vet / poison hotline.
 */

const REVIEWED = "2026-06-25";

const ASPCA_FOODS: ToxinSource = {
  name: "ASPCA Animal Poison Control — People Foods to Avoid",
  url: "https://www.aspca.org/pet-care/animal-poison-control/people-foods-avoid-feeding-your-pets",
};
const ASPCA_PLANTS: ToxinSource = {
  name: "ASPCA — Toxic and Non-Toxic Plants",
  url: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants",
};
const ASPCA_APCC: ToxinSource = {
  name: "ASPCA Animal Poison Control",
  url: "https://www.aspca.org/pet-care/animal-poison-control",
};
const PPH: ToxinSource = {
  name: "Pet Poison Helpline — Poisons",
  url: "https://www.petpoisonhelpline.com/poisons/",
};

/** Helper to keep entries terse + consistent. All default to pending vet review. */
function t(
  e: Omit<ToxinEntry, "lastReviewed" | "reviewStatus"> & Partial<Pick<ToxinEntry, "lastReviewed" | "reviewStatus">>,
): ToxinEntry {
  return { lastReviewed: REVIEWED, reviewStatus: "curated_public_source", ...e };
}

export const TOXINS: ToxinEntry[] = [
  // ── Foods (13) ──────────────────────────────────────────────
  t({
    slug: "xylitol",
    name: "Xylitol (birch sugar)",
    aliases: ["xylitol", "birch sugar", "sugar-free", "sugar free"],
    category: "food",
    species: "both",
    severity: "toxic",
    bodySystems: ["Metabolic", "Liver"],
    signs: ["weakness", "vomiting", "loss of coordination", "collapse", "seizures"],
    note: "A sweetener in gum, candy, peanut butter, and baked goods; even small amounts can cause a dangerous blood-sugar crash and liver failure in dogs.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "chocolate",
    name: "Chocolate / cocoa",
    aliases: ["chocolate", "cocoa", "cacao", "theobromine"],
    category: "food",
    species: "both",
    severity: "toxic",
    bodySystems: ["Heart", "Nervous"],
    signs: ["vomiting", "restlessness", "racing heart", "tremors", "seizures"],
    note: "Contains theobromine and caffeine; darker and baking chocolate are the most dangerous.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "grapes-raisins",
    name: "Grapes, raisins & currants",
    aliases: ["grape", "raisin", "currant", "sultana"],
    category: "food",
    species: "both",
    severity: "toxic",
    bodySystems: ["Kidney"],
    signs: ["vomiting", "lethargy", "reduced urination"],
    note: "Can cause sudden kidney failure; no amount is considered safe, and sensitivity varies between pets.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "allium",
    name: "Onion, garlic, chives & leeks",
    aliases: ["onion", "garlic", "chive", "leek", "shallot", "allium"],
    category: "food",
    species: "both",
    severity: "high",
    bodySystems: ["Blood (red cells)"],
    signs: ["weakness", "pale gums", "red or brown urine", "rapid breathing"],
    note: "Damage red blood cells; cats are especially sensitive. Powdered and cooked forms count too.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "macadamia",
    name: "Macadamia nuts",
    aliases: ["macadamia"],
    category: "food",
    species: "dog",
    severity: "high",
    bodySystems: ["Nervous", "Muscular"],
    signs: ["weakness in the back legs", "tremors", "vomiting", "fever"],
    note: "Cause weakness, tremors, and overheating in dogs.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "alcohol",
    name: "Alcohol (ethanol)",
    aliases: ["alcohol", "ethanol", "beer", "wine", "liquor"],
    category: "food",
    species: "both",
    severity: "toxic",
    bodySystems: ["Nervous", "Metabolic"],
    signs: ["stumbling", "disorientation", "vomiting", "slow breathing"],
    note: "Found in drinks, raw dough, and some products; even small amounts are dangerous to pets.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "caffeine",
    name: "Caffeine (coffee, tea, energy drinks)",
    aliases: ["caffeine", "coffee", "espresso", "energy drink"],
    category: "food",
    species: "both",
    severity: "high",
    bodySystems: ["Heart", "Nervous"],
    signs: ["restlessness", "racing heart", "tremors", "vomiting"],
    note: "A stimulant; grounds, tea bags, and pills are especially concentrated sources.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "yeast-dough",
    name: "Raw bread / yeast dough",
    aliases: ["raw dough", "yeast dough", "bread dough"],
    category: "food",
    species: "both",
    severity: "high",
    bodySystems: ["Stomach", "Metabolic"],
    signs: ["bloated or painful belly", "retching", "weakness", "disorientation"],
    note: "Rises and ferments in the stomach, producing gas and alcohol.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "salt-sodium",
    name: "Salt & salty dough ornaments",
    aliases: ["table salt", "salt dough", "play dough", "playdough", "rock salt", "ice melt"],
    category: "food",
    species: "both",
    severity: "high",
    bodySystems: ["Electrolyte", "Nervous"],
    signs: ["vomiting", "excessive thirst", "tremors", "stumbling"],
    note: "Large amounts of salt (table salt, salt-dough crafts, ice-melt) can dangerously raise blood sodium.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "moldy-food",
    name: "Moldy food & compost",
    aliases: ["moldy food", "mold", "compost"],
    category: "food",
    species: "both",
    severity: "high",
    bodySystems: ["Nervous"],
    signs: ["tremors", "agitation", "vomiting", "high temperature"],
    note: "Mold can contain tremorgenic mycotoxins that quickly cause tremors and seizures.",
    source: ASPCA_APCC,
  }),
  t({
    slug: "fatty-foods",
    name: "Fatty / greasy foods",
    aliases: ["fatty food", "grease", "bacon grease", "fried food", "drippings"],
    category: "food",
    species: "both",
    severity: "caution",
    bodySystems: ["Pancreas", "GI"],
    signs: ["vomiting", "diarrhea", "painful belly", "loss of appetite"],
    note: "Rich, fatty scraps can trigger pancreatitis, especially in prone dogs.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "raw-green-potato-tomato",
    name: "Green/raw potato & green tomato",
    aliases: ["green potato", "raw potato", "potato sprout", "green tomato", "solanine"],
    category: "food",
    species: "both",
    severity: "caution",
    bodySystems: ["GI", "Nervous"],
    signs: ["drooling", "vomiting", "diarrhea", "lethargy"],
    note: "Green parts, sprouts, and stems contain solanine; cooked ripe flesh is generally fine.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "avocado",
    name: "Avocado",
    aliases: ["avocado", "persin"],
    category: "food",
    species: "both",
    severity: "caution",
    bodySystems: ["GI"],
    signs: ["vomiting", "diarrhea"],
    note: "The flesh causes mild stomach upset in dogs and cats; the large pit is a choking and obstruction risk.",
    source: ASPCA_FOODS,
  }),

  // ── Plants (17) ─────────────────────────────────────────────
  t({
    slug: "lily-true",
    name: "Lily (true & day lilies)",
    aliases: ["lily", "lilies", "day lily", "easter lily", "tiger lily"],
    category: "plant",
    species: "cat",
    severity: "toxic",
    bodySystems: ["Kidney"],
    signs: ["drooling", "vomiting", "hiding", "reduced urination"],
    note: "For cats, every part — even pollen or vase water — can cause fatal kidney failure. Keep them out of the home entirely.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "sago-palm",
    name: "Sago palm (cycad)",
    aliases: ["sago", "cycad", "sago palm"],
    category: "plant",
    species: "both",
    severity: "toxic",
    bodySystems: ["Liver", "GI"],
    signs: ["vomiting", "dark stool", "jaundice", "weakness"],
    note: "All parts, especially the seeds, are highly toxic and can cause liver failure.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "oleander",
    name: "Oleander",
    aliases: ["oleander"],
    category: "plant",
    species: "both",
    severity: "toxic",
    bodySystems: ["Heart"],
    signs: ["drooling", "vomiting", "abnormal heart rate", "collapse"],
    note: "Contains cardiac glycosides that affect heart rhythm; all parts are toxic.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "azalea-rhododendron",
    name: "Azalea / rhododendron",
    aliases: ["azalea", "rhododendron"],
    category: "plant",
    species: "both",
    severity: "high",
    bodySystems: ["Heart", "GI"],
    signs: ["drooling", "vomiting", "diarrhea", "weakness"],
    note: "Grayanotoxins affect the gut and heart; even a few leaves can cause signs.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "autumn-crocus",
    name: "Autumn crocus (Colchicum)",
    aliases: ["autumn crocus", "colchicum", "colchicine"],
    category: "plant",
    species: "both",
    severity: "toxic",
    bodySystems: ["GI", "Multi-organ"],
    signs: ["drooling", "bloody vomiting or diarrhea", "weakness"],
    note: "Contains colchicine and can cause severe, sometimes delayed, multi-organ damage.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "tulip-hyacinth",
    name: "Tulip & hyacinth (bulbs)",
    aliases: ["tulip", "hyacinth"],
    category: "plant",
    species: "both",
    severity: "high",
    bodySystems: ["GI", "Heart"],
    signs: ["drooling", "vomiting", "diarrhea"],
    note: "The bulbs hold the most toxin; can cause heavy drooling and stomach upset.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "daffodil",
    name: "Daffodil (Narcissus)",
    aliases: ["daffodil", "narcissus", "jonquil"],
    category: "plant",
    species: "both",
    severity: "high",
    bodySystems: ["GI", "Heart"],
    signs: ["vomiting", "drooling", "belly pain", "abnormal heart rate"],
    note: "Bulbs are the most toxic part; can cause vomiting and heart or breathing changes.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "dieffenbachia",
    name: "Dieffenbachia (dumb cane)",
    aliases: ["dieffenbachia", "dumb cane"],
    category: "plant",
    species: "both",
    severity: "caution",
    bodySystems: ["Mouth", "GI"],
    signs: ["pawing at the mouth", "drooling", "swelling of the mouth or tongue", "vomiting"],
    note: "Insoluble calcium oxalate crystals cause intense mouth irritation and swelling.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "philodendron-pothos",
    name: "Philodendron & pothos",
    aliases: ["philodendron", "pothos", "devil's ivy"],
    category: "plant",
    species: "both",
    severity: "caution",
    bodySystems: ["Mouth", "GI"],
    signs: ["drooling", "pawing at the mouth", "vomiting"],
    note: "Common houseplants with oxalate crystals that irritate the mouth and throat.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "peace-lily",
    name: "Peace lily (Spathiphyllum)",
    aliases: ["peace lily", "spathiphyllum"],
    category: "plant",
    species: "both",
    severity: "caution",
    bodySystems: ["Mouth", "GI"],
    signs: ["drooling", "oral pain", "vomiting"],
    note: "Not a true lily — it irritates the mouth and throat rather than the kidneys, but still avoid it.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "cyclamen",
    name: "Cyclamen",
    aliases: ["cyclamen"],
    category: "plant",
    species: "both",
    severity: "high",
    bodySystems: ["Heart", "GI"],
    signs: ["drooling", "vomiting", "diarrhea", "abnormal heart rhythm"],
    note: "The roots and tubers are the most toxic part and can affect the heart.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "kalanchoe",
    name: "Kalanchoe",
    aliases: ["kalanchoe", "mother of millions"],
    category: "plant",
    species: "both",
    severity: "high",
    bodySystems: ["Heart", "GI"],
    signs: ["vomiting", "diarrhea", "abnormal heart rate"],
    note: "A popular flowering houseplant containing heart-affecting toxins.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "yew",
    name: "Yew (Taxus)",
    aliases: ["yew", "taxus"],
    category: "plant",
    species: "both",
    severity: "toxic",
    bodySystems: ["Heart", "Nervous"],
    signs: ["trembling", "difficulty breathing", "collapse", "sudden collapse"],
    note: "Contains taxines that affect the heart; all parts except the red flesh are toxic.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "foxglove",
    name: "Foxglove (Digitalis)",
    aliases: ["foxglove", "digitalis"],
    category: "plant",
    species: "both",
    severity: "toxic",
    bodySystems: ["Heart"],
    signs: ["drooling", "vomiting", "abnormal or slow heart rate", "weakness"],
    note: "Contains cardiac glycosides; all parts affect the heart.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "lily-of-the-valley",
    name: "Lily of the valley",
    aliases: ["lily of the valley", "convallaria"],
    category: "plant",
    species: "both",
    severity: "toxic",
    bodySystems: ["Heart"],
    signs: ["vomiting", "abnormal heart rate", "disorientation", "collapse"],
    note: "Despite the name it affects the heart, via cardiac glycosides.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "castor-bean",
    name: "Castor bean / ricin",
    aliases: ["castor bean", "ricin", "castor oil plant"],
    category: "plant",
    species: "both",
    severity: "toxic",
    bodySystems: ["GI", "Multi-organ"],
    signs: ["bloody diarrhea", "vomiting", "weakness", "tremors"],
    note: "The beans contain ricin, one of the most toxic plant compounds known.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "wild-mushrooms",
    name: "Wild mushrooms",
    aliases: ["mushroom", "toadstool", "amanita"],
    category: "plant",
    species: "both",
    severity: "toxic",
    bodySystems: ["Liver", "Nervous", "GI"],
    signs: ["vomiting", "diarrhea", "jaundice", "tremors", "seizures"],
    note: "Some wild or yard mushrooms cause liver failure or neurologic signs, and identification is unreliable — any ingestion is an emergency.",
    source: ASPCA_APCC,
  }),

  // ── Household / chemical (7) ────────────────────────────────
  t({
    slug: "antifreeze",
    name: "Antifreeze (ethylene glycol)",
    aliases: ["antifreeze", "ethylene glycol", "coolant", "radiator fluid"],
    category: "household",
    species: "both",
    severity: "toxic",
    bodySystems: ["Kidney"],
    signs: ["stumbling as if drunk", "excessive thirst", "vomiting", "later, reduced urination"],
    note: "Sweet-tasting and rapidly causes kidney failure; even tiny amounts are deadly, especially to cats. Acting fast is critical.",
    source: PPH,
  }),
  t({
    slug: "metaldehyde",
    name: "Slug & snail bait (metaldehyde)",
    aliases: ["metaldehyde", "slug bait", "snail bait"],
    category: "household",
    species: "both",
    severity: "toxic",
    bodySystems: ["Nervous"],
    signs: ["tremors", "twitching", "seizures", "high temperature"],
    note: "Causes severe tremors and seizures soon after ingestion.",
    source: PPH,
  }),
  t({
    slug: "bleach-cleaners",
    name: "Bleach & concentrated cleaners",
    aliases: ["bleach", "cleaner", "disinfectant", "drain cleaner", "ammonia"],
    category: "household",
    species: "both",
    severity: "high",
    bodySystems: ["GI", "Respiratory", "Skin"],
    signs: ["drooling", "mouth pain", "vomiting", "coughing"],
    note: "Concentrated or strongly acidic/alkaline cleaners are caustic and can burn the mouth, throat, and airways.",
    source: ASPCA_APCC,
  }),
  t({
    slug: "zinc",
    name: "Zinc (pennies, hardware, zinc creams)",
    aliases: ["zinc", "penny", "pennies", "zinc oxide", "diaper cream"],
    category: "household",
    species: "both",
    severity: "high",
    bodySystems: ["Blood (red cells)", "GI"],
    signs: ["vomiting", "pale or yellow gums", "red or brown urine", "weakness"],
    note: "Swallowed zinc objects and zinc-oxide creams can destroy red blood cells.",
    source: PPH,
  }),
  t({
    slug: "batteries",
    name: "Batteries (button / lithium)",
    aliases: ["battery", "batteries", "button battery", "coin cell"],
    category: "household",
    species: "both",
    severity: "high",
    bodySystems: ["Mouth", "GI"],
    signs: ["drooling", "mouth pain", "vomiting", "not eating"],
    note: "Cause caustic burns if chewed or swallowed; button/coin batteries are especially dangerous.",
    source: ASPCA_APCC,
  }),
  t({
    slug: "cannabis-thc",
    name: "Marijuana / THC (edibles & plants)",
    aliases: ["marijuana", "cannabis", "thc", "weed", "edible"],
    category: "household",
    species: "both",
    severity: "high",
    bodySystems: ["Nervous"],
    signs: ["stumbling", "dribbling urine", "dazed or sleepy", "low heart rate", "startling at sounds"],
    note: "THC affects the nervous system; edibles may also contain chocolate or xylitol, adding more risk.",
    source: PPH,
  }),
  t({
    slug: "fertilizer",
    name: "Fertilizers & plant foods",
    aliases: ["fertilizer", "plant food", "bone meal", "blood meal"],
    category: "household",
    species: "both",
    severity: "caution",
    bodySystems: ["GI"],
    signs: ["drooling", "vomiting", "diarrhea"],
    note: "Most cause stomach upset; some contain iron, pesticides, or 'meal' additives that are more dangerous.",
    source: ASPCA_APCC,
  }),

  // ── Medications, human (8) ──────────────────────────────────
  t({
    slug: "ibuprofen-nsaids",
    name: "Ibuprofen & naproxen (human NSAIDs)",
    aliases: ["ibuprofen", "advil", "motrin", "naproxen", "aleve", "nsaid"],
    category: "medication",
    species: "both",
    severity: "toxic",
    bodySystems: ["Kidney", "GI"],
    signs: ["vomiting (sometimes bloody)", "not eating", "lethargy", "increased thirst"],
    note: "Common human pain relievers; cause stomach ulcers and kidney failure. Cats are extremely sensitive.",
    source: PPH,
  }),
  t({
    slug: "acetaminophen",
    name: "Acetaminophen / paracetamol (Tylenol)",
    aliases: ["acetaminophen", "paracetamol", "tylenol"],
    category: "medication",
    species: "both",
    severity: "toxic",
    bodySystems: ["Blood", "Liver"],
    signs: ["pale, muddy, or bluish gums", "swelling of the face or paws", "trouble breathing", "vomiting"],
    note: "Even one tablet can be fatal to a cat by damaging red blood cells; dogs also risk liver damage.",
    source: PPH,
  }),
  t({
    slug: "aspirin",
    name: "Aspirin (human)",
    aliases: ["aspirin", "acetylsalicylic"],
    category: "medication",
    species: "both",
    severity: "high",
    bodySystems: ["GI", "Blood"],
    signs: ["vomiting", "dark stool", "loss of appetite", "weakness"],
    note: "Human aspirin can cause stomach ulcers and bleeding and should only be used under veterinary direction.",
    source: PPH,
  }),
  t({
    slug: "adhd-stimulants",
    name: "ADHD medications (amphetamine, methylphenidate)",
    aliases: ["adderall", "amphetamine", "methylphenidate", "ritalin", "vyvanse"],
    category: "medication",
    species: "both",
    severity: "toxic",
    bodySystems: ["Heart", "Nervous"],
    signs: ["hyperactivity", "racing heart", "tremors", "high temperature", "seizures"],
    note: "Even a small amount of these stimulants can be life-threatening.",
    source: PPH,
  }),
  t({
    slug: "antidepressants",
    name: "Antidepressants (SSRIs / SNRIs)",
    aliases: ["antidepressant", "ssri", "fluoxetine", "sertraline", "venlafaxine", "prozac"],
    category: "medication",
    species: "both",
    severity: "high",
    bodySystems: ["Nervous"],
    signs: ["agitation or sedation", "tremors", "high heart rate", "dilated pupils"],
    note: "Medications like fluoxetine and venlafaxine can cause serotonin-related toxicity.",
    source: PPH,
  }),
  t({
    slug: "decongestants",
    name: "Decongestants (pseudoephedrine)",
    aliases: ["pseudoephedrine", "sudafed", "decongestant", "phenylephrine"],
    category: "medication",
    species: "both",
    severity: "toxic",
    bodySystems: ["Heart", "Nervous"],
    signs: ["restlessness", "racing heart", "tremors", "high blood pressure"],
    note: "A potent stimulant found in many cold and allergy medicines.",
    source: PPH,
  }),
  t({
    slug: "iron-supplements",
    name: "Iron & prenatal vitamins",
    aliases: ["iron supplement", "ferrous", "prenatal vitamin"],
    category: "medication",
    species: "both",
    severity: "high",
    bodySystems: ["GI", "Liver", "Heart"],
    signs: ["vomiting (sometimes bloody)", "diarrhea", "lethargy"],
    note: "Iron-containing supplements can injure the stomach and, in larger amounts, organs. Plain pet vitamins are usually low-risk.",
    source: PPH,
  }),
  t({
    slug: "vitamin-d",
    name: "Vitamin D (high-strength supplements & some baits)",
    aliases: ["vitamin d", "cholecalciferol", "calcitriol"],
    category: "medication",
    species: "both",
    severity: "toxic",
    bodySystems: ["Kidney"],
    signs: ["increased thirst and urination", "vomiting", "weakness", "not eating"],
    note: "Excess vitamin D (from high-strength supplements or cholecalciferol bait) raises calcium and causes kidney failure.",
    source: PPH,
  }),

  // ── Rodenticides (2) ────────────────────────────────────────
  t({
    slug: "anticoagulant-rodenticide",
    name: "Anticoagulant rat / mouse bait",
    aliases: ["rat bait", "mouse bait", "rodenticide", "warfarin", "brodifacoum", "bromadiolone"],
    category: "rodenticide",
    species: "both",
    severity: "toxic",
    bodySystems: ["Blood (clotting)"],
    signs: ["weakness", "pale gums", "coughing", "bruising", "bleeding that won't stop"],
    note: "Stops blood from clotting; signs can be delayed several days. Bring the product packaging to the vet if you can.",
    source: PPH,
  }),
  t({
    slug: "bromethalin",
    name: "Bromethalin rat / mouse bait",
    aliases: ["bromethalin"],
    category: "rodenticide",
    species: "both",
    severity: "toxic",
    bodySystems: ["Brain", "Nervous"],
    signs: ["tremors", "stumbling", "weakness", "seizures"],
    note: "A non-anticoagulant bait that causes brain swelling; identifying the exact product matters, so keep the packaging.",
    source: PPH,
  }),

  // ── Essential oils (3) ──────────────────────────────────────
  t({
    slug: "tea-tree-oil",
    name: "Tea tree (melaleuca) oil",
    aliases: ["tea tree", "melaleuca", "tea tree oil"],
    category: "essential_oil",
    species: "both",
    severity: "toxic",
    bodySystems: ["Nervous", "Skin", "Liver"],
    signs: ["drooling", "weakness", "tremors", "wobbliness", "low temperature"],
    note: "Concentrated tea tree oil is toxic to dogs and cats even in small amounts, whether on the skin or swallowed.",
    source: PPH,
  }),
  t({
    slug: "pennyroyal-oil",
    name: "Pennyroyal oil",
    aliases: ["pennyroyal"],
    category: "essential_oil",
    species: "both",
    severity: "toxic",
    bodySystems: ["Liver"],
    signs: ["vomiting", "lethargy", "jaundice"],
    note: "An essential oil sometimes marketed for fleas that can cause liver failure.",
    source: PPH,
  }),
  t({
    slug: "wintergreen-oil",
    name: "Wintergreen oil",
    aliases: ["wintergreen", "methyl salicylate"],
    category: "essential_oil",
    species: "both",
    severity: "high",
    bodySystems: ["GI", "Blood"],
    signs: ["vomiting", "dark stool", "weakness"],
    note: "Contains salicylates (aspirin-like compounds) that are harmful to pets.",
    source: PPH,
  }),
];
