import type { ToxinCategory, ToxinEntry, ToxinSeverity, ToxinSource, ToxinSpeciesScope } from "./types";

/**
 * Petwell V1 local toxin reference — highest-priority toxins for dogs and cats,
 * curated from public veterinary poison-control sources (original Petwell
 * summaries; no copied passages). Seed set per the design spec's Phase 1.
 *
 * Severity is per-species. Every entry is `needs_review` (curated from a public
 * source, not yet clinician-verified) with `reviewedBy: null`. No dosing,
 * antidote, decontamination, or treatment text appears in any field.
 */

const REVIEWED = "2026-06-25";

const ASPCA_FOODS: ToxinSource = {
  name: "People Foods to Avoid Feeding Your Pets",
  publisher: "ASPCA Animal Poison Control",
  url: "https://www.aspca.org/pet-care/animal-poison-control/people-foods-avoid-feeding-your-pets",
  type: "poison_control_public",
};
const ASPCA_PLANTS: ToxinSource = {
  name: "Toxic and Non-Toxic Plants",
  publisher: "ASPCA",
  url: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants",
  type: "poison_control_public",
};
const ASPCA_APCC: ToxinSource = {
  name: "Animal Poison Control",
  publisher: "ASPCA",
  url: "https://www.aspca.org/pet-care/animal-poison-control",
  type: "poison_control_public",
};
const PPH: ToxinSource = {
  name: "Poisons (public list)",
  publisher: "Pet Poison Helpline",
  url: "https://www.petpoisonhelpline.com/poisons/",
  type: "poison_control_public",
};
const MERCK: ToxinSource = {
  name: "Merck Veterinary Manual — Toxicology",
  publisher: "Merck & Co.",
  url: "https://www.merckvetmanual.com/toxicology",
  type: "veterinary_manual",
};

interface Seed {
  slug: string;
  name: string;
  category: ToxinCategory;
  speciesScope: ToxinSpeciesScope;
  /** Sets both species unless dog/cat override. */
  severity?: ToxinSeverity;
  dog?: ToxinSeverity;
  cat?: ToxinSeverity;
  aliases: string[];
  bodySystems: string[];
  summary: string;
  clinicalSigns: string[];
  commonSources: string;
  doseWarning?: string;
  source: ToxinSource;
}

function t(e: Seed): ToxinEntry {
  return {
    slug: e.slug,
    name: e.name,
    category: e.category,
    speciesScope: e.speciesScope,
    dogSeverity: e.dog ?? e.severity ?? "unknown",
    catSeverity: e.cat ?? e.severity ?? "unknown",
    aliases: e.aliases,
    bodySystems: e.bodySystems,
    summary: e.summary,
    clinicalSigns: e.clinicalSigns,
    commonSources: e.commonSources,
    doseWarning: e.doseWarning,
    source: e.source,
    evidenceStatus: "needs_review",
    lastReviewed: REVIEWED,
    reviewedBy: null,
  };
}

export const TOXINS: ToxinEntry[] = [
  // ── Foods ───────────────────────────────────────────────────
  t({
    slug: "xylitol",
    name: "Xylitol (birch sugar)",
    category: "food",
    speciesScope: "both",
    dog: "emergency",
    cat: "caution",
    aliases: ["xylitol", "birch sugar", "gum sweetener", "sugar-free", "sugar free"],
    bodySystems: ["Metabolic", "Liver"],
    summary:
      "A sweetener in gum, candy, peanut butter, and baked goods. In dogs it can cause a rapid, dangerous blood-sugar crash and liver injury. Its effect in cats is not well established.",
    clinicalSigns: ["weakness", "wobbliness", "vomiting", "collapse", "seizures"],
    commonSources: "Sugar-free gum and candy, some peanut butters, baked goods, dental products.",
    doseWarning: "Even a small amount can affect a dog.",
    source: PPH,
  }),
  t({
    slug: "chocolate",
    name: "Chocolate / cocoa",
    category: "food",
    speciesScope: "both",
    severity: "high",
    aliases: ["chocolate", "cocoa", "cacao", "theobromine"],
    bodySystems: ["Heart", "Nervous"],
    summary: "Contains theobromine and caffeine. Darker and baking chocolate carry the most risk; large amounts can be an emergency.",
    clinicalSigns: ["vomiting", "restlessness", "racing heart", "tremors", "seizures"],
    commonSources: "Candy, baking chocolate, cocoa powder, chocolate-covered snacks.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "grapes-raisins",
    name: "Grapes, raisins & currants",
    category: "food",
    speciesScope: "both",
    dog: "emergency",
    cat: "high",
    aliases: ["grape", "raisin", "currant", "sultana"],
    bodySystems: ["Kidney"],
    summary: "Can cause sudden kidney injury in dogs; sensitivity varies a lot between individuals.",
    clinicalSigns: ["vomiting", "lethargy", "reduced urination"],
    commonSources: "Fresh grapes, raisins, trail mix, baked goods, some snack bars.",
    doseWarning: "No amount is known to be safe.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "allium",
    name: "Onion, garlic, chives & leeks",
    category: "food",
    speciesScope: "both",
    severity: "high",
    aliases: ["onion", "garlic", "chive", "leek", "shallot", "allium"],
    bodySystems: ["Blood (red cells)"],
    summary: "Damage red blood cells; cats are especially sensitive. Powdered and cooked forms count too.",
    clinicalSigns: ["weakness", "pale gums", "red or brown urine", "rapid breathing"],
    commonSources: "Cooked dishes, broths, baby food, onion/garlic powder, some supplements.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "macadamia",
    name: "Macadamia nuts",
    category: "food",
    speciesScope: "both",
    dog: "high",
    cat: "unknown",
    aliases: ["macadamia"],
    bodySystems: ["Nervous", "Muscular"],
    summary: "Cause weakness, tremors, and overheating in dogs; effects in cats are not reported.",
    clinicalSigns: ["weakness in the back legs", "tremors", "vomiting", "fever"],
    commonSources: "Mixed nuts, cookies, candies, baked goods.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "alcohol",
    name: "Alcohol (ethanol)",
    category: "food",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["alcohol", "ethanol", "beer", "wine", "liquor"],
    bodySystems: ["Nervous", "Metabolic"],
    summary: "Found in drinks, raw dough, and some products. Even small amounts are dangerous to pets.",
    clinicalSigns: ["stumbling", "disorientation", "vomiting", "slow breathing"],
    commonSources: "Alcoholic drinks, raw bread dough, rum-soaked desserts, some sanitizers.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "caffeine",
    name: "Caffeine (coffee, tea, energy drinks)",
    category: "food",
    speciesScope: "both",
    severity: "high",
    aliases: ["caffeine", "coffee", "espresso", "energy drink"],
    bodySystems: ["Heart", "Nervous"],
    summary: "A stimulant; grounds, tea bags, and pills are especially concentrated.",
    clinicalSigns: ["restlessness", "racing heart", "tremors", "vomiting"],
    commonSources: "Coffee, grounds, tea, energy drinks, caffeine pills, pre-workout powders.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "yeast-dough",
    name: "Raw bread / yeast dough",
    category: "food",
    speciesScope: "both",
    severity: "high",
    aliases: ["raw dough", "yeast dough", "bread dough"],
    bodySystems: ["Stomach", "Metabolic"],
    summary: "Rises and ferments in the stomach, producing gas and alcohol.",
    clinicalSigns: ["bloated or painful belly", "retching", "weakness", "disorientation"],
    commonSources: "Rising bread, pizza, or roll dough left within reach.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "salt-sodium",
    name: "Salt & salty dough ornaments",
    category: "food",
    speciesScope: "both",
    severity: "high",
    aliases: ["table salt", "salt dough", "play dough", "playdough", "rock salt", "ice melt"],
    bodySystems: ["Electrolyte", "Nervous"],
    summary: "Large amounts of salt (table salt, salt-dough crafts, ice-melt) can dangerously raise blood sodium.",
    clinicalSigns: ["vomiting", "excessive thirst", "tremors", "stumbling"],
    commonSources: "Salt-dough ornaments, ice-melt, large amounts of salty food, sea water.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "moldy-food",
    name: "Moldy food & compost",
    category: "food",
    speciesScope: "both",
    severity: "high",
    aliases: ["moldy food", "mold", "compost"],
    bodySystems: ["Nervous"],
    summary: "Mold can contain tremorgenic mycotoxins that quickly cause tremors and seizures.",
    clinicalSigns: ["tremors", "agitation", "vomiting", "high temperature"],
    commonSources: "Garbage, compost bins, spoiled dairy, moldy bread or nuts.",
    source: ASPCA_APCC,
  }),
  t({
    slug: "fatty-foods",
    name: "Fatty / greasy foods",
    category: "food",
    speciesScope: "both",
    severity: "caution",
    aliases: ["fatty food", "grease", "bacon grease", "fried food", "drippings"],
    bodySystems: ["Pancreas", "GI"],
    summary: "Rich, fatty scraps can trigger pancreatitis, especially in prone dogs.",
    clinicalSigns: ["vomiting", "diarrhea", "painful belly", "loss of appetite"],
    commonSources: "Bacon, fat trimmings, fried foods, gravy, holiday table scraps.",
    source: ASPCA_FOODS,
  }),
  t({
    slug: "raw-green-potato-tomato",
    name: "Green/raw potato & green tomato",
    category: "food",
    speciesScope: "both",
    severity: "caution",
    aliases: ["green potato", "raw potato", "potato sprout", "green tomato", "solanine"],
    bodySystems: ["GI", "Nervous"],
    summary: "Green parts, sprouts, and stems contain solanine; cooked ripe flesh is generally fine.",
    clinicalSigns: ["drooling", "vomiting", "diarrhea", "lethargy"],
    commonSources: "Sprouted or green potatoes, potato plants, unripe tomatoes and their plants.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "avocado",
    name: "Avocado",
    category: "food",
    speciesScope: "both",
    severity: "caution",
    aliases: ["avocado", "persin"],
    bodySystems: ["GI"],
    summary: "The flesh causes mild stomach upset in dogs and cats; the large pit is a choking and obstruction risk.",
    clinicalSigns: ["vomiting", "diarrhea"],
    commonSources: "Guacamole, avocado flesh, pits, and the plant.",
    source: ASPCA_FOODS,
  }),

  // ── Plants ──────────────────────────────────────────────────
  t({
    slug: "lily-true",
    name: "Lily (true & day lilies)",
    category: "plant",
    speciesScope: "both",
    cat: "emergency",
    dog: "caution",
    aliases: ["lily", "lilies", "day lily", "easter lily", "tiger lily"],
    bodySystems: ["Kidney"],
    summary:
      "For CATS, every part — even pollen or vase water — can cause fatal kidney failure; keep them out of the home entirely. In dogs, true lilies usually cause only mild stomach upset.",
    clinicalSigns: ["drooling", "vomiting", "hiding", "reduced urination"],
    commonSources: "Cut-flower bouquets, Easter lilies, garden day lilies, the vase water.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "sago-palm",
    name: "Sago palm (cycad)",
    category: "plant",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["sago", "cycad", "sago palm"],
    bodySystems: ["Liver", "GI"],
    summary: "All parts, especially the seeds, are highly toxic and can cause liver failure.",
    clinicalSigns: ["vomiting", "dark stool", "jaundice", "weakness"],
    commonSources: "Ornamental houseplants and landscaping, especially in warm climates.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "oleander",
    name: "Oleander",
    category: "plant",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["oleander"],
    bodySystems: ["Heart"],
    summary: "Contains cardiac glycosides that affect heart rhythm; all parts are toxic.",
    clinicalSigns: ["drooling", "vomiting", "abnormal heart rate", "collapse"],
    commonSources: "Outdoor landscaping shrubs, clippings, and bouquets.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "azalea-rhododendron",
    name: "Azalea / rhododendron",
    category: "plant",
    speciesScope: "both",
    severity: "high",
    aliases: ["azalea", "rhododendron"],
    bodySystems: ["Heart", "GI"],
    summary: "Grayanotoxins affect the gut and heart; even a few leaves can cause signs.",
    clinicalSigns: ["drooling", "vomiting", "diarrhea", "weakness"],
    commonSources: "Garden and landscaping shrubs, clippings.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "autumn-crocus",
    name: "Autumn crocus (Colchicum)",
    category: "plant",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["autumn crocus", "colchicum", "colchicine"],
    bodySystems: ["GI", "Multi-organ"],
    summary: "Contains colchicine and can cause severe, sometimes delayed, multi-organ damage.",
    clinicalSigns: ["drooling", "bloody vomiting or diarrhea", "weakness"],
    commonSources: "Fall-blooming garden bulbs.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "tulip-hyacinth",
    name: "Tulip & hyacinth (bulbs)",
    category: "plant",
    speciesScope: "both",
    severity: "high",
    aliases: ["tulip", "hyacinth"],
    bodySystems: ["GI", "Heart"],
    summary: "The bulbs hold the most toxin; can cause heavy drooling and stomach upset.",
    clinicalSigns: ["drooling", "vomiting", "diarrhea"],
    commonSources: "Spring garden bulbs, potted bulbs, planting season.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "daffodil",
    name: "Daffodil (Narcissus)",
    category: "plant",
    speciesScope: "both",
    severity: "high",
    aliases: ["daffodil", "narcissus", "jonquil"],
    bodySystems: ["GI", "Heart"],
    summary: "Bulbs are the most toxic part; can cause vomiting and heart or breathing changes.",
    clinicalSigns: ["vomiting", "drooling", "belly pain", "abnormal heart rate"],
    commonSources: "Spring bulbs and cut flowers.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "dieffenbachia",
    name: "Dieffenbachia (dumb cane)",
    category: "plant",
    speciesScope: "both",
    severity: "caution",
    aliases: ["dieffenbachia", "dumb cane"],
    bodySystems: ["Mouth", "GI"],
    summary: "Insoluble calcium oxalate crystals cause intense mouth irritation and swelling.",
    clinicalSigns: ["pawing at the mouth", "drooling", "swelling of the mouth or tongue", "vomiting"],
    commonSources: "Common leafy houseplant.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "philodendron-pothos",
    name: "Philodendron & pothos",
    category: "plant",
    speciesScope: "both",
    severity: "caution",
    aliases: ["philodendron", "pothos", "devil's ivy"],
    bodySystems: ["Mouth", "GI"],
    summary: "Common houseplants with oxalate crystals that irritate the mouth and throat.",
    clinicalSigns: ["drooling", "pawing at the mouth", "vomiting"],
    commonSources: "Trailing/hanging houseplants.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "peace-lily",
    name: "Peace lily (Spathiphyllum)",
    category: "plant",
    speciesScope: "both",
    severity: "caution",
    aliases: ["peace lily", "spathiphyllum"],
    bodySystems: ["Mouth", "GI"],
    summary: "Not a true lily — it irritates the mouth and throat rather than the kidneys, but still avoid it.",
    clinicalSigns: ["drooling", "oral pain", "vomiting"],
    commonSources: "Flowering houseplant.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "cyclamen",
    name: "Cyclamen",
    category: "plant",
    speciesScope: "both",
    severity: "high",
    aliases: ["cyclamen"],
    bodySystems: ["Heart", "GI"],
    summary: "The roots and tubers are the most toxic part and can affect the heart.",
    clinicalSigns: ["drooling", "vomiting", "diarrhea", "abnormal heart rhythm"],
    commonSources: "Flowering potted houseplant, popular in winter.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "kalanchoe",
    name: "Kalanchoe",
    category: "plant",
    speciesScope: "both",
    severity: "high",
    aliases: ["kalanchoe", "mother of millions"],
    bodySystems: ["Heart", "GI"],
    summary: "A popular flowering houseplant containing heart-affecting toxins.",
    clinicalSigns: ["vomiting", "diarrhea", "abnormal heart rate"],
    commonSources: "Flowering succulent houseplant.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "yew",
    name: "Yew (Taxus)",
    category: "plant",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["yew", "taxus"],
    bodySystems: ["Heart", "Nervous"],
    summary: "Contains taxines that affect the heart; all parts except the red flesh are toxic.",
    clinicalSigns: ["trembling", "difficulty breathing", "sudden collapse"],
    commonSources: "Evergreen landscaping shrubs and clippings.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "foxglove",
    name: "Foxglove (Digitalis)",
    category: "plant",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["foxglove", "digitalis"],
    bodySystems: ["Heart"],
    summary: "Contains cardiac glycosides; all parts affect the heart.",
    clinicalSigns: ["drooling", "vomiting", "abnormal or slow heart rate", "weakness"],
    commonSources: "Garden flowers and bouquets.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "lily-of-the-valley",
    name: "Lily of the valley",
    category: "plant",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["lily of the valley", "convallaria"],
    bodySystems: ["Heart"],
    summary: "Despite the name it affects the heart, via cardiac glycosides.",
    clinicalSigns: ["vomiting", "abnormal heart rate", "disorientation", "collapse"],
    commonSources: "Shade garden ground cover and bouquets.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "castor-bean",
    name: "Castor bean / ricin",
    category: "plant",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["castor bean", "ricin", "castor oil plant"],
    bodySystems: ["GI", "Multi-organ"],
    summary: "The beans contain ricin, one of the most toxic plant compounds known.",
    clinicalSigns: ["bloody diarrhea", "vomiting", "weakness", "tremors"],
    commonSources: "Ornamental plants, some mulch, jewelry made from seeds.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "aloe",
    name: "Aloe vera",
    category: "plant",
    speciesScope: "both",
    severity: "caution",
    aliases: ["aloe", "aloe vera"],
    bodySystems: ["GI"],
    summary: "The latex/gel can cause stomach upset in dogs and cats.",
    clinicalSigns: ["vomiting", "lethargy", "diarrhea"],
    commonSources: "Houseplants and some topical gels.",
    source: ASPCA_PLANTS,
  }),
  t({
    slug: "jade-plant",
    name: "Jade plant",
    category: "plant",
    speciesScope: "both",
    severity: "caution",
    aliases: ["jade plant", "crassula", "money plant"],
    bodySystems: ["GI", "Nervous"],
    summary: "A common succulent that can cause stomach upset and incoordination; the exact toxin is unknown.",
    clinicalSigns: ["vomiting", "lethargy", "incoordination"],
    commonSources: "Popular succulent houseplant.",
    source: ASPCA_PLANTS,
  }),

  // ── Recreational / environmental ────────────────────────────
  t({
    slug: "cannabis-thc",
    name: "Marijuana / THC (edibles & plants)",
    category: "recreational",
    speciesScope: "both",
    severity: "high",
    aliases: ["marijuana", "cannabis", "thc", "weed", "pot", "edible"],
    bodySystems: ["Nervous"],
    summary: "THC affects the nervous system; edibles may also contain chocolate or xylitol, adding more risk.",
    clinicalSigns: ["stumbling", "dribbling urine", "dazed or sleepy", "low heart rate", "startling at sounds"],
    commonSources: "Edibles, dried plant, concentrates, second-hand smoke.",
    source: PPH,
  }),
  t({
    slug: "wild-mushrooms",
    name: "Wild mushrooms",
    category: "recreational",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["mushroom", "toadstool", "amanita"],
    bodySystems: ["Liver", "Nervous", "GI"],
    summary:
      "Some wild or yard mushrooms cause liver failure or neurologic signs, and identification is unreliable — any ingestion is an emergency.",
    clinicalSigns: ["vomiting", "diarrhea", "jaundice", "tremors", "seizures"],
    commonSources: "Lawns, woods, and damp shaded areas after rain.",
    source: ASPCA_APCC,
  }),
  t({
    slug: "nicotine",
    name: "Nicotine (cigarettes, vapes, gum, patches)",
    category: "recreational",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["nicotine", "cigarette", "vape", "e-liquid", "nicotine gum", "nicotine patch", "tobacco"],
    bodySystems: ["Heart", "Nervous"],
    summary: "Concentrated nicotine (vape liquid, gum, patches, butts) is rapidly toxic to pets.",
    clinicalSigns: ["drooling", "vomiting", "racing or abnormal heart rate", "tremors", "weakness"],
    commonSources: "Cigarettes and butts, vape liquid, nicotine gum and patches.",
    source: PPH,
  }),
  t({
    slug: "blue-green-algae",
    name: "Blue-green algae (cyanobacteria)",
    category: "recreational",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["blue-green algae", "cyanobacteria", "pond scum", "algae bloom"],
    bodySystems: ["Liver", "Nervous"],
    summary: "Toxic algae blooms in warm, stagnant water can cause rapid liver failure or neurologic collapse.",
    clinicalSigns: ["vomiting", "diarrhea", "weakness", "tremors", "collapse"],
    commonSources: "Warm, still ponds and lakes with green/blue surface scum.",
    source: ASPCA_APCC,
  }),

  // ── Household / chemical ────────────────────────────────────
  t({
    slug: "antifreeze",
    name: "Antifreeze (ethylene glycol)",
    category: "household",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["antifreeze", "ethylene glycol", "coolant", "radiator fluid"],
    bodySystems: ["Kidney"],
    summary:
      "Sweet-tasting and rapidly causes kidney failure; even a tiny amount is deadly, especially to cats. Time matters enormously.",
    clinicalSigns: ["stumbling as if drunk", "excessive thirst", "vomiting", "later, reduced urination"],
    commonSources: "Radiator coolant leaks/spills, garages, driveways.",
    doseWarning: "Even a small lick can be fatal — do not wait.",
    source: MERCK,
  }),
  t({
    slug: "metaldehyde",
    name: "Slug & snail bait (metaldehyde)",
    category: "household",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["metaldehyde", "slug bait", "snail bait"],
    bodySystems: ["Nervous"],
    summary: "Causes severe tremors and seizures soon after ingestion.",
    clinicalSigns: ["tremors", "twitching", "seizures", "high temperature"],
    commonSources: "Garden slug/snail pellets.",
    source: PPH,
  }),
  t({
    slug: "bleach-cleaners",
    name: "Bleach & concentrated cleaners",
    category: "household",
    speciesScope: "both",
    severity: "high",
    aliases: ["bleach", "cleaner", "disinfectant", "drain cleaner", "ammonia"],
    bodySystems: ["GI", "Respiratory", "Skin"],
    summary: "Concentrated or strongly acidic/alkaline cleaners are caustic and can burn the mouth, throat, and airways.",
    clinicalSigns: ["drooling", "mouth pain", "vomiting", "coughing"],
    commonSources: "Household cleaning products, especially undiluted.",
    source: ASPCA_APCC,
  }),
  t({
    slug: "laundry-pods",
    name: "Laundry & dishwasher pods",
    category: "household",
    speciesScope: "both",
    severity: "high",
    aliases: ["laundry pod", "detergent pod", "dishwasher pod", "liquitab"],
    bodySystems: ["GI", "Respiratory"],
    summary: "The concentrated detergent bursts under pressure and can cause vomiting and airway irritation.",
    clinicalSigns: ["drooling", "vomiting", "coughing or gagging", "squinting if it contacts the eyes"],
    commonSources: "Single-use laundry and dishwasher detergent packets.",
    source: PPH,
  }),
  t({
    slug: "zinc",
    name: "Zinc (pennies, hardware, zinc creams)",
    category: "household",
    speciesScope: "both",
    severity: "high",
    aliases: ["zinc", "penny", "pennies", "zinc oxide", "diaper cream"],
    bodySystems: ["Blood (red cells)", "GI"],
    summary: "Swallowed zinc objects and zinc-oxide creams can destroy red blood cells.",
    clinicalSigns: ["vomiting", "pale or yellow gums", "red or brown urine", "weakness"],
    commonSources: "Pennies minted after 1982, nuts/bolts, zinc-oxide skin creams.",
    source: PPH,
  }),
  t({
    slug: "batteries",
    name: "Batteries (button / lithium)",
    category: "household",
    speciesScope: "both",
    severity: "high",
    aliases: ["battery", "batteries", "button battery", "coin cell"],
    bodySystems: ["Mouth", "GI"],
    summary: "Cause caustic burns if chewed or swallowed; button/coin batteries are especially dangerous.",
    clinicalSigns: ["drooling", "mouth pain", "vomiting", "not eating"],
    commonSources: "Remotes, toys, key fobs, hearing aids, electronics.",
    source: ASPCA_APCC,
  }),
  t({
    slug: "fertilizer",
    name: "Fertilizers & plant foods",
    category: "household",
    speciesScope: "both",
    severity: "caution",
    aliases: ["fertilizer", "plant food", "bone meal", "blood meal"],
    bodySystems: ["GI"],
    summary: "Most cause stomach upset; some contain iron, pesticides, or 'meal' additives that are more dangerous.",
    clinicalSigns: ["drooling", "vomiting", "diarrhea"],
    commonSources: "Lawn and garden fertilizers, bone/blood meal amendments.",
    source: ASPCA_APCC,
  }),
  t({
    slug: "anticoagulant-rodenticide",
    name: "Anticoagulant rat / mouse bait",
    category: "household",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["rat bait", "mouse bait", "rat poison", "rodenticide", "warfarin", "brodifacoum", "bromadiolone"],
    bodySystems: ["Blood (clotting)"],
    summary: "Stops blood from clotting; signs can be delayed several days. Bring the product packaging to the vet if you can.",
    clinicalSigns: ["weakness", "pale gums", "coughing", "bruising", "bleeding that won't stop"],
    commonSources: "Rodent bait stations in homes, garages, and sheds.",
    source: PPH,
  }),
  t({
    slug: "bromethalin",
    name: "Bromethalin rat / mouse bait",
    category: "household",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["bromethalin", "rat poison", "mouse poison"],
    bodySystems: ["Brain", "Nervous"],
    summary: "A non-anticoagulant bait that causes brain swelling; identifying the exact product matters, so keep the packaging.",
    clinicalSigns: ["tremors", "stumbling", "weakness", "seizures"],
    commonSources: "Rodent bait stations; the active ingredient varies by brand.",
    source: PPH,
  }),

  // ── Human medications ───────────────────────────────────────
  t({
    slug: "ibuprofen-nsaids",
    name: "Ibuprofen & naproxen (human NSAIDs)",
    category: "medication",
    speciesScope: "both",
    dog: "high",
    cat: "emergency",
    aliases: ["ibuprofen", "advil", "motrin", "naproxen", "aleve", "nsaid", "pain reliever"],
    bodySystems: ["Kidney", "GI"],
    summary: "Common human pain relievers; cause stomach ulcers and kidney injury. Cats are extremely sensitive.",
    clinicalSigns: ["vomiting (sometimes bloody)", "not eating", "lethargy", "increased thirst"],
    commonSources: "Human medicine cabinets, dropped pills, purses.",
    source: PPH,
  }),
  t({
    slug: "acetaminophen",
    name: "Acetaminophen / paracetamol (Tylenol)",
    category: "medication",
    speciesScope: "both",
    cat: "emergency",
    dog: "high",
    aliases: ["acetaminophen", "paracetamol", "tylenol", "pain reliever"],
    bodySystems: ["Blood", "Liver"],
    summary: "Even one tablet can be fatal to a CAT by damaging red blood cells; dogs also risk liver damage.",
    clinicalSigns: ["pale, muddy, or bluish gums", "swelling of the face or paws", "trouble breathing", "vomiting"],
    commonSources: "Human pain/cold medicines, combination products.",
    doseWarning: "There is no safe at-home amount for cats.",
    source: PPH,
  }),
  t({
    slug: "aspirin",
    name: "Aspirin (human)",
    category: "medication",
    speciesScope: "both",
    severity: "high",
    aliases: ["aspirin", "acetylsalicylic", "pain reliever"],
    bodySystems: ["GI", "Blood"],
    summary: "Human aspirin can cause stomach ulcers and bleeding and should only be used under veterinary direction.",
    clinicalSigns: ["vomiting", "dark stool", "loss of appetite", "weakness"],
    commonSources: "Human medicine cabinets; some combination products.",
    source: PPH,
  }),
  t({
    slug: "adhd-stimulants",
    name: "ADHD medications (amphetamine, methylphenidate)",
    category: "medication",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["adderall", "amphetamine", "methylphenidate", "ritalin", "vyvanse"],
    bodySystems: ["Heart", "Nervous"],
    summary: "Even a small amount of these stimulants can be life-threatening.",
    clinicalSigns: ["hyperactivity", "racing heart", "tremors", "high temperature", "seizures"],
    commonSources: "Prescription stimulant pills.",
    source: PPH,
  }),
  t({
    slug: "antidepressants",
    name: "Antidepressants (SSRIs / SNRIs)",
    category: "medication",
    speciesScope: "both",
    severity: "high",
    aliases: ["antidepressant", "ssri", "fluoxetine", "sertraline", "venlafaxine", "prozac"],
    bodySystems: ["Nervous"],
    summary: "Medications like fluoxetine and venlafaxine can cause serotonin-related toxicity.",
    clinicalSigns: ["agitation or sedation", "tremors", "high heart rate", "dilated pupils"],
    commonSources: "Prescription pills and pill organizers.",
    source: PPH,
  }),
  t({
    slug: "benzodiazepines-sleep",
    name: "Sleep & anxiety medications (benzodiazepines, zolpidem)",
    category: "medication",
    speciesScope: "both",
    severity: "high",
    aliases: ["benzodiazepine", "xanax", "alprazolam", "diazepam", "valium", "zolpidem", "ambien", "sleep aid"],
    bodySystems: ["Nervous"],
    summary: "Can cause heavy sedation — or paradoxical agitation — and unsteadiness.",
    clinicalSigns: ["sedation", "stumbling", "agitation", "weakness"],
    commonSources: "Prescription sleep and anxiety medications.",
    source: PPH,
  }),
  t({
    slug: "decongestants",
    name: "Decongestants (pseudoephedrine)",
    category: "medication",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["pseudoephedrine", "sudafed", "decongestant", "phenylephrine"],
    bodySystems: ["Heart", "Nervous"],
    summary: "A potent stimulant found in many cold and allergy medicines.",
    clinicalSigns: ["restlessness", "racing heart", "tremors", "high blood pressure"],
    commonSources: "Cold, sinus, and allergy medicines.",
    source: PPH,
  }),

  // ── Supplements / vet-product misuse ────────────────────────
  t({
    slug: "iron-supplements",
    name: "Iron & prenatal vitamins",
    category: "supplement",
    speciesScope: "both",
    severity: "high",
    aliases: ["iron supplement", "ferrous", "prenatal vitamin"],
    bodySystems: ["GI", "Liver", "Heart"],
    summary: "Iron-containing supplements can injure the stomach and, in larger amounts, organs. Plain pet vitamins are usually low-risk.",
    clinicalSigns: ["vomiting (sometimes bloody)", "diarrhea", "lethargy"],
    commonSources: "Prenatal and iron supplements, some multivitamins.",
    source: PPH,
  }),
  t({
    slug: "vitamin-d",
    name: "Vitamin D (high-strength supplements & some baits)",
    category: "supplement",
    speciesScope: "both",
    severity: "high",
    aliases: ["vitamin d", "cholecalciferol", "calcitriol"],
    bodySystems: ["Kidney"],
    summary: "Excess vitamin D (from high-strength supplements or cholecalciferol bait) raises calcium and can cause kidney failure.",
    clinicalSigns: ["increased thirst and urination", "vomiting", "weakness", "not eating"],
    commonSources: "High-strength vitamin D supplements, psoriasis creams, some rodent bait.",
    source: PPH,
  }),

  // ── Essential oils ──────────────────────────────────────────
  t({
    slug: "tea-tree-oil",
    name: "Tea tree (melaleuca) oil",
    category: "essential_oil",
    speciesScope: "both",
    dog: "high",
    cat: "emergency",
    aliases: ["tea tree", "melaleuca", "tea tree oil"],
    bodySystems: ["Nervous", "Skin", "Liver"],
    summary: "Concentrated tea tree oil is toxic to dogs and cats even in small amounts, whether on the skin or swallowed; cats are most at risk.",
    clinicalSigns: ["drooling", "weakness", "tremors", "wobbliness", "low temperature"],
    commonSources: "Pure essential oil, some 'natural' skin and flea products.",
    source: PPH,
  }),
  t({
    slug: "pennyroyal-oil",
    name: "Pennyroyal oil",
    category: "essential_oil",
    speciesScope: "both",
    severity: "emergency",
    aliases: ["pennyroyal"],
    bodySystems: ["Liver"],
    summary: "An essential oil sometimes marketed for fleas that can cause liver failure.",
    clinicalSigns: ["vomiting", "lethargy", "jaundice"],
    commonSources: "Herbal flea remedies and concentrated oils.",
    source: PPH,
  }),
  t({
    slug: "wintergreen-oil",
    name: "Wintergreen oil",
    category: "essential_oil",
    speciesScope: "both",
    severity: "high",
    aliases: ["wintergreen", "methyl salicylate"],
    bodySystems: ["GI", "Blood"],
    summary: "Contains salicylates (aspirin-like compounds) that are harmful to pets.",
    clinicalSigns: ["vomiting", "dark stool", "weakness"],
    commonSources: "Pure essential oil, some muscle rubs and liniments.",
    source: PPH,
  }),
  t({
    slug: "eucalyptus-oil",
    name: "Eucalyptus & citrus oils",
    category: "essential_oil",
    speciesScope: "both",
    dog: "caution",
    cat: "high",
    aliases: ["eucalyptus", "citrus oil", "d-limonene", "limonene", "peppermint oil"],
    bodySystems: ["Nervous", "Skin", "GI"],
    summary: "Diffused or applied essential oils can irritate or sicken pets; cats cannot process many oils and are most at risk.",
    clinicalSigns: ["drooling", "wobbliness", "vomiting", "skin or eye irritation"],
    commonSources: "Diffusers, cleaning products, 'natural' sprays, concentrated oils.",
    source: ASPCA_APCC,
  }),
];
