import type { BiologicalSystem, CatalogItem, EvidenceGrade } from "./types";

/** The nine biological systems and their functional-medicine-style patterns. */
export const BIOLOGICAL_SYSTEMS: BiologicalSystem[] = [
  { id: "gut", label: "Gut & digestion", patterns: ["Microbiome imbalance (dysbiosis)", "Food sensitivity", "Digestive inflammation", "Maldigestion"] },
  { id: "skin", label: "Skin & allergy", patterns: ["Allergic / atopic inflammation", "Skin-barrier dysfunction", "Damp-heat pattern (TCM)", "Secondary skin infection"] },
  { id: "hepatic", label: "Pancreas, liver & gallbladder", patterns: ["Fat maldigestion", "Hepatic stress", "Biliary stagnation (TCM: Liver Qi)"] },
  { id: "renal", label: "Kidney & urinary", patterns: ["Dehydration / concentrated urine", "Lower-urinary inflammation", "Increased renal workload"] },
  { id: "immune", label: "Immune & inflammation", patterns: ["Over-active inflammatory response", "Oxidative stress", "Immune dysregulation"] },
  { id: "metabolic", label: "Endocrine & metabolic", patterns: ["Weight / insulin dysregulation", "Low metabolic reserve", "Thyroid-related (vet-led)"] },
  { id: "msk", label: "Musculoskeletal & pain", patterns: ["Joint wear / osteoarthritis", "Soft-tissue strain", "Stiffness (TCM: Wind-Damp / Blood stasis)"] },
  { id: "dental", label: "Dental & oral", patterns: ["Periodontal inflammation", "Oral pain"] },
  { id: "behavior", label: "Stress & behavior", patterns: ["Stress / anxiety response", "Gut-brain axis", "Environmental triggers"] },
];

/** Map a triage concern module id to a biological system. */
export const TRIAGE_TO_SYSTEM: Record<string, string> = {
  diarrhea: "gut",
  vomiting: "gut",
  appetite: "gut",
  skin: "skin",
  ear: "skin",
  eye: "immune",
  urinary: "renal",
  mobility: "msk",
  teeth: "dental",
  energy: "metabolic",
  generic: "immune",
};

export const EVIDENCE_GRADES: Record<EvidenceGrade, { label: string; note: string }> = {
  A: { label: "Strong", note: "Supported by controlled veterinary studies or established practice." },
  B: { label: "Moderate", note: "Supported by some studies plus a sound mechanism." },
  C: { label: "Limited / emerging", note: "Small studies or plausible traditional use." },
  D: { label: "Traditional", note: "Historical / TCM use with minimal modern data." },
};

export function getSystem(id: string): BiologicalSystem {
  return BIOLOGICAL_SYSTEMS.find((s) => s.id === id) ?? BIOLOGICAL_SYSTEMS[4]; // immune = general fallback
}

/**
 * Curated natural-support catalog. Species safety, evidence grade,
 * contraindications, med interactions, and ask-vet flags are intrinsic to each
 * item; the engine applies the additional global gates (emergency, cat-stricter).
 */
export const CATALOG: CatalogItem[] = [
  {
    id: "omega3",
    name: "Omega-3 fish oil (EPA/DHA)",
    kind: "supplement",
    systems: ["skin", "immune", "msk", "renal"],
    benefit: "May help support the skin barrier, joint comfort, and a balanced inflammatory response.",
    speciesSafety: { dog: "safe", cat: "safe" },
    evidence: "B",
    contraindications: ["Known bleeding disorder", "Scheduled surgery"],
    medInteractions: ["Anticoagulants", "High-dose NSAIDs"],
    askVetFirst: false,
    source: "Veterinary nutrition reviews on omega-3s in dermatologic and renal support.",
  },
  {
    id: "probiotic",
    name: "Multi-strain probiotic",
    kind: "supplement",
    systems: ["gut", "immune"],
    benefit: "May help support a balanced gut microbiome during and after digestive upset.",
    speciesSafety: { dog: "safe", cat: "safe" },
    evidence: "B",
    contraindications: ["Significant immune suppression"],
    medInteractions: ["Separate from antibiotics by a few hours"],
    askVetFirst: false,
    source: "Veterinary probiotic trials in acute diarrhea.",
  },
  {
    id: "pumpkin",
    name: "Plain pumpkin (soluble fiber)",
    kind: "food",
    systems: ["gut"],
    benefit: "May help support stool consistency as a gentle soluble fiber.",
    speciesSafety: { dog: "safe", cat: "safe" },
    evidence: "C",
    contraindications: [],
    medInteractions: [],
    askVetFirst: false,
    source: "Clinical nutrition guidance on soluble fiber.",
    thermalNature: "neutral",
    flavor: "Sweet",
    tcmPattern: "Harmonizes the Spleen & Stomach; supports stool",
    prep: "Plain cooked purée (no spice/sugar); small spoonfuls.",
  },
  {
    id: "glucosamine",
    name: "Glucosamine + chondroitin",
    kind: "supplement",
    systems: ["msk"],
    benefit: "May help support joint comfort and mobility over time.",
    speciesSafety: { dog: "safe", cat: "safe" },
    evidence: "B",
    contraindications: ["Shellfish allergy (some sources)"],
    medInteractions: [],
    askVetFirst: false,
    source: "Veterinary osteoarthritis literature.",
  },
  {
    id: "l_theanine",
    name: "Calming nutraceutical (L-theanine)",
    kind: "supplement",
    systems: ["behavior"],
    benefit: "May help support calm behavior during predictable stressful events.",
    speciesSafety: { dog: "safe", cat: "caution" },
    evidence: "C",
    contraindications: [],
    medInteractions: ["Additive with sedatives / behavior meds"],
    askVetFirst: false,
    source: "Behavioral nutraceutical studies.",
  },
  {
    id: "digestive_enzymes",
    name: "Digestive enzymes",
    kind: "supplement",
    systems: ["hepatic", "gut"],
    benefit: "May help support fat and protein digestion in some pets, under veterinary guidance.",
    speciesSafety: { dog: "caution", cat: "caution" },
    evidence: "C",
    contraindications: ["Do NOT use during an acute pancreatitis flare"],
    medInteractions: [],
    askVetFirst: true,
    source: "Used under veterinary guidance for exocrine pancreatic insufficiency.",
  },
  {
    id: "milk_thistle",
    name: "Milk thistle (silymarin)",
    kind: "herb",
    systems: ["hepatic"],
    benefit: "May help support the liver during recovery, alongside veterinary care.",
    speciesSafety: { dog: "caution", cat: "caution" },
    evidence: "C",
    contraindications: ["Pregnancy"],
    medInteractions: ["May affect liver-metabolized drugs — time separately"],
    askVetFirst: true,
    source: "Hepatoprotective traditional use with emerging data.",
  },
  {
    id: "cranberry",
    name: "Cranberry extract",
    kind: "supplement",
    systems: ["renal"],
    benefit: "May help support lower-urinary-tract health in some pets.",
    speciesSafety: { dog: "safe", cat: "caution" },
    evidence: "C",
    contraindications: ["History of calcium-oxalate stones"],
    medInteractions: [],
    askVetFirst: false,
    source: "Urinary-adjunct literature (mixed results).",
  },
  {
    id: "slippery_elm",
    name: "Slippery elm bark",
    kind: "herb",
    systems: ["gut"],
    benefit: "May help soothe the digestive tract during mild upset (demulcent).",
    speciesSafety: { dog: "caution", cat: "caution" },
    evidence: "C",
    contraindications: [],
    medInteractions: ["Give 1–2 h apart from oral medications (absorption)"],
    askVetFirst: true,
    source: "Traditional demulcent use.",
    thermalNature: "neutral",
    flavor: "Sweet",
    tcmPattern: "Moistens and soothes; supports the Stomach",
  },
  {
    id: "chamomile",
    name: "Chamomile",
    kind: "herb",
    systems: ["behavior", "gut"],
    benefit: "May help support calm and mild digestive comfort.",
    speciesSafety: { dog: "caution", cat: "caution" },
    evidence: "D",
    contraindications: ["Ragweed-family allergy"],
    medInteractions: ["Additive with sedatives"],
    askVetFirst: true,
    source: "Traditional calming use.",
    thermalNature: "cooling",
    flavor: "Bitter / sweet",
    tcmPattern: "Calms the Liver; clears mild Heat",
  },
  {
    id: "turmeric",
    name: "Turmeric / curcumin",
    kind: "herb",
    systems: ["msk", "immune"],
    benefit: "May help support a balanced inflammatory response in some dogs.",
    speciesSafety: { dog: "caution", cat: "avoid" },
    evidence: "C",
    contraindications: ["Bleeding disorder", "Gallbladder obstruction"],
    medInteractions: ["Anticoagulants", "NSAIDs"],
    askVetFirst: true,
    source: "Anti-inflammatory research (limited oral bioavailability).",
    thermalNature: "warming",
    flavor: "Bitter / pungent",
    tcmPattern: "Moves Blood and Qi; warms",
  },
  // ── TCM "food as medicine" whole foods ──
  {
    id: "white_fish",
    name: "Plain cooked white fish (cod / pollock)",
    kind: "food",
    systems: ["gut", "renal"],
    benefit: "A gentle, lean protein that may support bland recovery diets.",
    speciesSafety: { dog: "safe", cat: "safe" },
    evidence: "C",
    contraindications: ["Known fish allergy"],
    medInteractions: [],
    askVetFirst: false,
    source: "TCM food energetics and bland-diet practice.",
    thermalNature: "neutral",
    flavor: "Sweet",
    tcmPattern: "Tonifies Qi; gentle on the Spleen & Stomach",
    prep: "Boil or steam plain — no oil, salt, onion, or garlic.",
  },
  {
    id: "bone_broth",
    name: "Plain bone broth",
    kind: "food",
    systems: ["gut", "msk"],
    benefit: "Hydrating and palatable; may help support intake during recovery.",
    speciesSafety: { dog: "safe", cat: "caution" },
    evidence: "D",
    contraindications: ["Must be low-sodium and onion/garlic-free"],
    medInteractions: [],
    askVetFirst: false,
    source: "Traditional use plus supportive-nutrition practice.",
    thermalNature: "warming",
    flavor: "Sweet / salty",
    tcmPattern: "Nourishes Yin & Blood; supports the Spleen",
    prep: "Simmer plain bones; cool and skim the fat for low-fat needs.",
  },
  {
    id: "sweet_potato",
    name: "Cooked sweet potato",
    kind: "food",
    systems: ["gut", "metabolic"],
    benefit: "A digestible complex carbohydrate for bland support (mainly dogs).",
    speciesSafety: { dog: "safe", cat: "caution" },
    evidence: "C",
    contraindications: ["Use sparingly for weight or diabetic management"],
    medInteractions: [],
    askVetFirst: false,
    source: "Bland-diet practice and TCM food energetics.",
    thermalNature: "neutral",
    flavor: "Sweet",
    tcmPattern: "Tonifies Spleen Qi",
    prep: "Cooked, plain, mashed; small amounts.",
  },
  {
    id: "sardines",
    name: "Sardines packed in water",
    kind: "food",
    systems: ["skin", "msk", "immune"],
    benefit: "An omega-3-rich whole food that may support skin and joints.",
    speciesSafety: { dog: "safe", cat: "safe" },
    evidence: "C",
    contraindications: ["Known fish allergy", "Use small portions (calories/sodium)"],
    medInteractions: [],
    askVetFirst: false,
    source: "Whole-food omega-3 source.",
    thermalNature: "warming",
    flavor: "Salty / sweet",
    tcmPattern: "Tonifies Qi & Blood; warms",
    prep: "Plain, in water (not oil/brine); a small portion as topper.",
  },
  {
    id: "duck",
    name: "Cooked duck (novel / cooling protein)",
    kind: "food",
    systems: ["skin", "immune"],
    benefit: "A cooling novel protein that may suit pets with heat-pattern itchy skin.",
    speciesSafety: { dog: "safe", cat: "safe" },
    evidence: "D",
    contraindications: ["Known poultry allergy"],
    medInteractions: [],
    askVetFirst: false,
    source: "TCM food energetics (cooling proteins for damp-heat).",
    thermalNature: "cooling",
    flavor: "Sweet / salty",
    tcmPattern: "Tonifies Yin; clears Heat",
    prep: "Plain cooked, skin/fat removed for low-fat needs.",
  },
];

export function catalogById(id: string): CatalogItem | undefined {
  return CATALOG.find((c) => c.id === id);
}

export function itemsForSystem(systemId: string): CatalogItem[] {
  return CATALOG.filter((c) => c.systems.includes(systemId));
}
