-- Seed the Longevity catalog tables (queryable mirror of the in-app engines).
-- Idempotent: upsert by slug for catalogs; replace program task templates.

-- ── Meal plans ───────────────────────────────────────────────
insert into public.meal_plans
  (slug, title, condition_slug, species, who_for, calories_note, fat_note, protein_note, fiber_note, hydration_note, thermal_nature, tcm_pattern, prep, evidence, needs_nutritionist, cat_caution, contraindications, commercial, homemade)
values
  ($q$pancreatitis_lowfat$q$, $q$Low-fat pancreatitis support$q$, $q$pancreatitis$q$, $q$both$q$,
   $q$Dogs recovering from or prone to pancreatitis, once your vet says it's safe to eat.$q$,
   $q$Small, frequent meals to a vet-set daily calorie target.$q$,
   $q$Low fat — for dogs, a therapeutic low-fat diet or roughly <10% fat on a dry-matter basis.$q$,
   $q$Lean, gentle proteins (white fish, skinless poultry breast, very lean turkey).$q$,
   $q$Moderate, digestible fiber; avoid rich or greasy add-ins.$q$,
   $q$Keep water available; a little plain low-sodium broth can encourage drinking.$q$,
   $q$neutral$q$, $q$Supports the Spleen & Stomach without adding Damp/greasy load$q$,
   $q$Boil or steam plain; skim all fat; no oil, salt, onion, or garlic.$q$, $q$B$q$, true,
   $q$Cats are different: feline pancreatitis is usually NOT managed with aggressive low-fat dieting, and keeping a cat eating is critical. Never withhold food from a cat — follow your vet's feline-specific plan.$q$,
   array[$q$Acute/severe symptoms need veterinary care first — do not home-manage$q$, $q$No fatty treats, oils, cheese, or table scraps$q$],
   array[$q$Veterinary therapeutic low-fat GI diets$q$, $q$Low-fat 'sensitive digestion' formulas (confirm fat % with your vet)$q$],
   array[$q$Skinless white fish or turkey breast + a digestible carb (white rice or potato), measured$q$, $q$Always vet-formulated for the long term$q$]),
  ($q$gentle_digestion$q$, $q$Gentle digestion (gut reset) meals$q$, $q$chronic_diarrhea$q$, $q$both$q$,
   $q$Pets with a mild, non-emergency tummy upset, with your vet's okay.$q$,
   $q$Maintain normal calories split into small, frequent meals.$q$,
   $q$Lower fat to ease digestion during recovery.$q$,
   $q$A single lean, easily digested protein (white fish, skinless chicken/turkey).$q$,
   $q$A little soluble fiber (plain pumpkin) can firm stool.$q$,
   $q$Watch hydration closely; offer water often.$q$,
   $q$neutral$q$, $q$Harmonizes the Spleen & Stomach; easy to digest$q$,
   $q$Boil plain; no seasoning, oil, onion, or garlic.$q$, $q$B$q$, false, null,
   array[$q$Blood in stool, repeated vomiting, or lethargy → vet, not home care$q$, $q$Not for long-term feeding without balancing$q$],
   array[$q$Veterinary GI 'gentle' diets$q$, $q$Limited-ingredient sensitive-stomach formulas$q$],
   array[$q$Plain white fish or turkey + white rice, 2–3 days, then transition back over 5–7 days$q$, $q$Add 1 tsp–1 tbsp plain pumpkin by size$q$]),
  ($q$cooling_itch$q$, $q$Cooling meals for itchy / inflammatory patterns$q$, $q$itchy_skin$q$, $q$both$q$,
   $q$Itchy, 'hot' pets with heat-pattern skin (red, inflamed), alongside a vet work-up.$q$,
   $q$Maintain a healthy weight to reduce inflammatory load.$q$,
   $q$Moderate, with omega-3-rich choices to support the skin barrier.$q$,
   $q$Cooling novel proteins in TCM (duck, white fish, rabbit); minimize warming proteins (lamb, chicken) if they aggravate itch.$q$,
   $q$Standard digestible fiber.$q$, $q$Keep well hydrated to support skin.$q$,
   $q$cooling$q$, $q$Clears Damp-Heat; tonifies Yin$q$, $q$Cook plain; remove skin/excess fat; no spices.$q$, $q$C$q$, true, null,
   array[$q$Not a substitute for a vet-guided elimination diet$q$, $q$Watch for any food the pet is allergic to$q$],
   array[$q$Novel-protein or hydrolyzed diets (vet-guided)$q$, $q$Fish-based limited-ingredient formulas$q$],
   array[$q$Duck or white fish + cooling carbs, vet-formulated$q$, $q$A fish-oil topper for EPA/DHA$q$]),
  ($q$warming_support$q$, $q$Warming, supportive meals (cold / low-energy)$q$, null, $q$both$q$,
   $q$Pets who run cold, seem low-energy, or are recovering and need gentle warmth (TCM lens).$q$,
   $q$Adequate calories to rebuild condition; avoid overfeeding.$q$,
   $q$Moderate, healthy fats for energy unless your vet advises low-fat.$q$,
   $q$Warming proteins in TCM (chicken, turkey, beef, lamb) as tolerated.$q$,
   $q$Gentle, cooked vegetables.$q$, $q$Warm (not hot) food and broth can aid intake.$q$,
   $q$warming$q$, $q$Warms the Middle; tonifies Qi & Blood$q$, $q$Serve warm; cook plain without onion/garlic.$q$, $q$D$q$, true, null,
   array[$q$Not for pancreatitis-prone or overweight pets without vet guidance$q$, $q$Avoid in 'hot'/inflamed patterns$q$],
   array[$q$Balanced maintenance diets; warm slightly before serving$q$],
   array[$q$Lightly cooked chicken or turkey + cooked squash/sweet potato, vet-formulated$q$, $q$Plain low-sodium bone broth as a topper$q$]),
  ($q$kidney_hydration_meals$q$, $q$Kidney hydration support meals$q$, $q$kidney_hydration$q$, $q$both$q$,
   $q$Pets needing urinary/renal support; if kidney disease is diagnosed, follow a renal diet.$q$,
   $q$Enough calories to hold a healthy weight (appetite can dip with kidney issues).$q$,
   $q$Adequate fat for palatable calories.$q$,
   $q$If diagnosed CKD, controlled, high-quality protein per a renal diet; otherwise a balanced diet.$q$,
   $q$Standard; some renal diets add specific fibers.$q$,
   $q$Maximize moisture — favor wet/canned food and add water or low-sodium broth.$q$,
   $q$neutral$q$, $q$Tonifies Yin & Fluids; eases the Kidney workload$q$, $q$Add warm water to wet food to make a 'soup'.$q$, $q$A$q$, true,
   $q$Cats hide kidney issues well and resist diet changes — transition slowly and never let a cat stop eating.$q$,
   array[$q$Straining or unable to urinate (esp. male cat) → emergency, not diet$q$, $q$Don't restrict protein without a diagnosis and vet guidance$q$],
   array[$q$Veterinary renal therapeutic diets (controlled phosphorus/protein)$q$, $q$Wet/canned formats for moisture$q$],
   array[$q$Renal homemade diets MUST be formulated by a veterinary nutritionist$q$, $q$Add water to every meal$q$]),
  ($q$weight_satiety$q$, $q$Weight-loss satiety meals$q$, $q$obesity_metabolic$q$, $q$both$q$,
   $q$Overweight pets on a vet-guided weight-loss plan.$q$,
   $q$A vet-set calorie deficit; measure every meal with a scale.$q$,
   $q$Lower fat to cut calories while keeping protein up.$q$,
   $q$Higher protein to preserve muscle during loss.$q$,
   $q$Higher fiber for fullness (satiety).$q$, $q$Add water/low-cal broth to bulk meals.$q$,
   $q$neutral$q$, $q$Drains Damp; supports the Spleen's transformation of food$q$, $q$Measure portions by weight; bulk with water or green beans.$q$, $q$A$q$, true,
   $q$Feline weight loss must be slow (~0.5–1% body weight/week) and vet-supervised to avoid hepatic lipidosis.$q$,
   array[$q$Cats must lose weight slowly — crash-dieting risks fatal hepatic lipidosis$q$, $q$Rule out metabolic disease first$q$],
   array[$q$Veterinary 'metabolic' / weight-management diets (high protein, high fiber)$q$],
   array[$q$Lean protein + green beans to bulk volume, vet-formulated$q$, $q$Swap treats for counted veggies$q$]),
  ($q$allergy_elimination$q$, $q$Allergy elimination-trial meals$q$, $q$itchy_skin$q$, $q$both$q$,
   $q$Pets doing a vet-guided 8–12 week elimination trial for suspected food allergy.$q$,
   $q$Maintain normal calories; only the trial diet for the full window.$q$,
   $q$Per the chosen trial diet.$q$,
   $q$A single novel or hydrolyzed protein the pet hasn't eaten before — strictly one source.$q$,
   $q$Per the trial diet.$q$, $q$Normal hydration.$q$,
   $q$neutral$q$, $q$Removes provoking foods to calm Damp-Heat$q$, $q$Strict single-protein prep; nothing else by mouth.$q$, $q$A$q$, true, null,
   array[$q$No other foods, treats, flavored meds, or table scraps during the trial — even one slip invalidates it$q$, $q$Must be vet-guided to interpret results$q$],
   array[$q$Hydrolyzed or true novel-protein veterinary diets$q$],
   array[$q$A single novel protein + single carb, vet-formulated for the trial$q$]),
  ($q$senior_maintenance_meals$q$, $q$Senior pet maintenance meals$q$, $q$senior_maintenance$q$, $q$both$q$,
   $q$Senior pets without an acute problem, to support healthy aging.$q$,
   $q$Adjust to maintain ideal body condition (metabolism often slows).$q$,
   $q$Moderate, with omega-3s for joints and cognition.$q$,
   $q$Adequate high-quality protein to preserve muscle (don't over-restrict unless your vet advises).$q$,
   $q$Digestible fiber for regularity.$q$, $q$Encourage moisture, especially for senior cats.$q$,
   $q$neutral$q$, $q$Tonifies Qi, Blood & Kidney essence for graceful aging$q$, $q$Soften kibble with warm water if dental comfort is an issue.$q$, $q$B$q$, false,
   $q$Senior cats benefit from extra moisture and twice-yearly checks; weigh regularly to catch loss early.$q$,
   array[$q$Tailor to any diagnosed condition (kidney, heart) with your vet$q$],
   array[$q$Senior / mature maintenance diets$q$, $q$Wet formats for hydration$q$],
   array[$q$Balanced senior recipes, vet-formulated$q$, $q$Add a fish-oil topper if your vet agrees$q$])
on conflict (slug) do update set
  title = excluded.title, condition_slug = excluded.condition_slug, species = excluded.species,
  who_for = excluded.who_for, calories_note = excluded.calories_note, fat_note = excluded.fat_note,
  protein_note = excluded.protein_note, fiber_note = excluded.fiber_note, hydration_note = excluded.hydration_note,
  thermal_nature = excluded.thermal_nature, tcm_pattern = excluded.tcm_pattern, prep = excluded.prep,
  evidence = excluded.evidence, needs_nutritionist = excluded.needs_nutritionist, cat_caution = excluded.cat_caution,
  contraindications = excluded.contraindications, commercial = excluded.commercial, homemade = excluded.homemade;

-- ── Environment risks ────────────────────────────────────────
insert into public.environment_risks (slug, label, question, why, safer_step, allergy_relevant, cat_severity, dog_severity)
values
  ($q$cleaning$q$, $q$Cleaning products$q$, $q$Do you use strong or scented floor/surface cleaners where your pet walks or rests?$q$, $q$Residues on floors transfer to paws and coats and are then licked off.$q$, $q$Rinse floors after cleaning; choose fragrance-free, pet-safe cleaners.$q$, true, $q$caution$q$, $q$caution$q$),
  ($q$fragrance$q$, $q$Fragrances, candles & plug-ins$q$, $q$Are there scented candles, sprays, or plug-in air fresheners in shared rooms?$q$, $q$Airborne fragrances can irritate airways and sensitive skin.$q$, $q$Switch to unscented; ventilate well; keep pets out of freshly scented rooms.$q$, true, $q$high$q$, $q$caution$q$),
  ($q$essential_oils$q$, $q$Essential oils & diffusers$q$, $q$Do you diffuse or apply essential oils (tea tree, citrus, eucalyptus, peppermint, etc.)?$q$, $q$Many oils are toxic to pets — cats especially can't process them and can be harmed by vapor or skin contact.$q$, $q$For cats, stop diffusing oils entirely. For dogs, avoid direct contact and diffuse only with vet guidance and ventilation.$q$, true, $q$high$q$, $q$caution$q$),
  ($q$laundry$q$, $q$Laundry detergent & dryer sheets$q$, $q$Is pet bedding washed with scented detergent or dryer sheets?$q$, $q$Fragrance and residues sit against the skin all day.$q$, $q$Wash bedding in fragrance-free detergent; skip dryer sheets.$q$, true, $q$caution$q$, $q$caution$q$),
  ($q$lawn$q$, $q$Lawn & garden chemicals$q$, $q$Are herbicides, fertilizers, or pesticides used where your pet walks?$q$, $q$Chemicals stick to paws and fur and are ingested during grooming.$q$, $q$Keep pets off treated areas until dry/watered in; wipe paws after walks.$q$, false, $q$caution$q$, $q$high$q$),
  ($q$flea_tick$q$, $q$Flea / tick products$q$, $q$Are you using the correct species-specific flea/tick product at the right dose?$q$, $q$Dog products containing permethrin can be deadly to cats.$q$, $q$Never use a dog flea product on a cat; confirm species and weight with your vet.$q$, false, $q$high$q$, $q$caution$q$),
  ($q$bowls$q$, $q$Food & water bowls$q$, $q$Are you using plastic bowls?$q$, $q$Scratched plastic harbors bacteria and is linked to chin/skin irritation.$q$, $q$Switch to stainless steel or ceramic; wash daily.$q$, true, $q$caution$q$, $q$caution$q$),
  ($q$mold_dust$q$, $q$Mold, dust & dust mites$q$, $q$Any damp spots, visible mold, or heavy household dust?$q$, $q$Mold and dust mites are common airway and skin allergens.$q$, $q$Fix damp areas; vacuum and damp-dust often; consider a HEPA filter.$q$, true, $q$caution$q$, $q$caution$q$),
  ($q$bedding$q$, $q$Bedding & resting areas$q$, $q$How often is your pet's bedding washed?$q$, $q$Pollen, dander, and allergens build up in unwashed bedding.$q$, $q$Wash bedding weekly in hot, fragrance-free water during allergy season.$q$, true, $q$info$q$, $q$caution$q$),
  ($q$litter$q$, $q$Litter type (cats)$q$, $q$Is the litter heavily scented or very dusty?$q$, $q$Scented or dusty litter can irritate feline airways and deter litter-box use.$q$, $q$Use unscented, low-dust litter; scoop daily; provide enough boxes.$q$, true, $q$caution$q$, $q$info$q$),
  ($q$air_quality$q$, $q$Air quality & smoke$q$, $q$Is there tobacco/vape smoke or poor ventilation indoors?$q$, $q$Secondhand smoke is linked to respiratory and some cancers in pets.$q$, $q$Keep the home smoke-free; ventilate; consider an air purifier.$q$, true, $q$high$q$, $q$high$q$)
on conflict (slug) do update set
  label = excluded.label, question = excluded.question, why = excluded.why, safer_step = excluded.safer_step,
  allergy_relevant = excluded.allergy_relevant, cat_severity = excluded.cat_severity, dog_severity = excluded.dog_severity;

-- ── Marketplace products ─────────────────────────────────────
insert into public.marketplace_products (slug, category, name, species, evidence, transparency, ingredient_quality, lab_tested, reported_outcomes, fit_tags, blurb)
values
  ($q$food_lowfat_gi$q$, $q$food$q$, $q$Vet low-fat GI diet (example)$q$, $q$both$q$, $q$A$q$, 5, 4, true, 4, array[$q$low-fat$q$,$q$gi$q$,$q$pancreatitis$q$], $q$Therapeutic low-fat formula for fat-sensitive pets.$q$),
  ($q$food_novel$q$, $q$food$q$, $q$Novel-protein limited-ingredient food (example)$q$, $q$both$q$, $q$B$q$, 4, 4, true, 4, array[$q$novel-protein$q$,$q$skin$q$,$q$allergy$q$], $q$Single novel protein for elimination trials.$q$),
  ($q$food_renal$q$, $q$food$q$, $q$Renal support diet (example)$q$, $q$both$q$, $q$A$q$, 5, 4, true, 4, array[$q$renal$q$,$q$senior$q$], $q$Controlled phosphorus and protein for diagnosed kidney support.$q$),
  ($q$treat_single$q$, $q$treats$q$, $q$Single-ingredient lean treat (example)$q$, $q$both$q$, $q$C$q$, 5, 5, false, 3, array[$q$low-fat$q$,$q$single-ingredient$q$], $q$One named protein, nothing else.$q$),
  ($q$treat_dental$q$, $q$treats$q$, $q$VOHC-accepted dental chew (example)$q$, $q$dog$q$, $q$B$q$, 4, 3, false, 4, array[$q$dental$q$], $q$Accepted for tartar control; count the calories.$q$),
  ($q$prob_multi$q$, $q$probiotics$q$, $q$Multi-strain vet probiotic (example)$q$, $q$both$q$, $q$B$q$, 5, 4, true, 4, array[$q$gut$q$,$q$gi$q$], $q$Strains studied in pets, with CFU guarantees.$q$),
  ($q$enz_pancreatic$q$, $q$enzymes$q$, $q$Pancreatic enzyme powder (example)$q$, $q$both$q$, $q$C$q$, 4, 4, false, 3, array[$q$enzymes$q$,$q$epi$q$], $q$For diagnosed EPI under veterinary guidance.$q$),
  ($q$omega_fish$q$, $q$omega3$q$, $q$Triglyceride-form fish oil (example)$q$, $q$both$q$, $q$B$q$, 5, 5, true, 4, array[$q$skin$q$,$q$joint$q$,$q$omega3$q$], $q$Third-party tested EPA/DHA for skin and joints.$q$),
  ($q$supp_joint$q$, $q$supplements$q$, $q$Glucosamine + chondroitin (example)$q$, $q$both$q$, $q$B$q$, 4, 4, false, 3, array[$q$joint$q$,$q$senior$q$], $q$Joint-comfort support over time.$q$),
  ($q$groom_shampoo$q$, $q$grooming$q$, $q$Fragrance-free gentle shampoo (example)$q$, $q$both$q$, $q$C$q$, 5, 4, false, 4, array[$q$skin$q$,$q$fragrance-free$q$], $q$Soothing, no added fragrance for sensitive skin.$q$),
  ($q$clean_petsafe$q$, $q$cleaning$q$, $q$Fragrance-free pet-safe cleaner (example)$q$, $q$both$q$, $q$C$q$, 5, 4, false, 3, array[$q$fragrance-free$q$,$q$home$q$], $q$Low-residue, unscented surface cleaner.$q$),
  ($q$bowl_steel$q$, $q$bowls$q$, $q$Stainless-steel bowl set (example)$q$, $q$both$q$, $q$C$q$, 5, 5, false, 4, array[$q$bowls$q$,$q$skin$q$], $q$Non-porous and easy to sanitize daily.$q$)
on conflict (slug) do update set
  category = excluded.category, name = excluded.name, species = excluded.species, evidence = excluded.evidence,
  transparency = excluded.transparency, ingredient_quality = excluded.ingredient_quality, lab_tested = excluded.lab_tested,
  reported_outcomes = excluded.reported_outcomes, fit_tags = excluded.fit_tags, blurb = excluded.blurb;

-- ── Program task templates (replace) ─────────────────────────
delete from public.program_tasks;
insert into public.program_tasks (template_id, kind, label, sort) values
  ($q$stool_reset_7$q$, $q$daily$q$, $q$Feed the bland/gentle diet in small, frequent meals$q$, 0),
  ($q$stool_reset_7$q$, $q$daily$q$, $q$Add a little plain pumpkin if advised$q$, 1),
  ($q$stool_reset_7$q$, $q$daily$q$, $q$Offer fresh water and watch hydration$q$, 2),
  ($q$stool_reset_7$q$, $q$daily$q$, $q$Score today's stool (1–5)$q$, 3),
  ($q$itch_tracker_14$q$, $q$daily$q$, $q$Rate itch 0–10$q$, 0),
  ($q$itch_tracker_14$q$, $q$daily$q$, $q$Wipe paws/coat after walks$q$, 1),
  ($q$itch_tracker_14$q$, $q$daily$q$, $q$Note foods, treats, and any new products$q$, 2),
  ($q$itch_tracker_14$q$, $q$daily$q$, $q$Photograph any flares$q$, 3),
  ($q$weight_tuneup_30$q$, $q$daily$q$, $q$Measure every meal to the calorie target$q$, 0),
  ($q$weight_tuneup_30$q$, $q$daily$q$, $q$Keep treats within the daily budget$q$, 1),
  ($q$weight_tuneup_30$q$, $q$daily$q$, $q$Add gentle activity (walk or play)$q$, 2),
  ($q$weight_tuneup_30$q$, $q$daily$q$, $q$Log treats and activity$q$, 3),
  ($q$senior_cat_hydration_14$q$, $q$daily$q$, $q$Add water/low-sodium broth to wet food$q$, 0),
  ($q$senior_cat_hydration_14$q$, $q$daily$q$, $q$Refresh all water stations$q$, 1),
  ($q$senior_cat_hydration_14$q$, $q$daily$q$, $q$Note water intake and litter-box output$q$, 2),
  ($q$senior_cat_hydration_14$q$, $q$daily$q$, $q$Weigh-in (every few days)$q$, 3),
  ($q$pancreatitis_recovery_14$q$, $q$daily$q$, $q$Feed the low-fat plan in small, frequent meals$q$, 0),
  ($q$pancreatitis_recovery_14$q$, $q$daily$q$, $q$Absolutely no fatty treats or table scraps$q$, 1),
  ($q$pancreatitis_recovery_14$q$, $q$daily$q$, $q$Watch for vomiting or belly discomfort$q$, 2),
  ($q$pancreatitis_recovery_14$q$, $q$daily$q$, $q$Log appetite, stool, and energy$q$, 3),
  ($q$allergy_elimination_56$q$, $q$daily$q$, $q$Feed ONLY the trial diet — no other foods, treats, or flavored meds$q$, 0),
  ($q$allergy_elimination_56$q$, $q$daily$q$, $q$Rate itch 0–10$q$, 1),
  ($q$allergy_elimination_56$q$, $q$daily$q$, $q$Guard against scavenged food and table scraps$q$, 2),
  ($q$allergy_elimination_56$q$, $q$daily$q$, $q$Note any skin/ear/GI changes$q$, 3),
  ($q$arthritis_mobility_30$q$, $q$daily$q$, $q$Keep to the measured, lean-weight feeding plan$q$, 0),
  ($q$arthritis_mobility_30$q$, $q$daily$q$, $q$Do gentle, low-impact activity$q$, 1),
  ($q$arthritis_mobility_30$q$, $q$daily$q$, $q$Use ramps/rugs; keep rest areas warm and soft$q$, 2),
  ($q$arthritis_mobility_30$q$, $q$daily$q$, $q$Note stiffness after rest and on stairs$q$, 3);
