-- 0027_holistic_library_seed.sql
-- Holistic library expansion: herbs 4→29, natural remedies 3→27, supplement
-- ingredients 6→41, contraindications 8→45, medication interactions 6→43.
-- Authored in the 2026-09-07 research session, applied live there, and ported
-- here byte-for-byte via server-side SQL generation (md5-verified).
--
-- Conventions (match 0013/0015): benefits use "may help support…" phrasing;
-- dog_safety/cat_safety ∈ safe|caution|avoid; evidence_grade A–D per
-- evidence_grades; systems arrays use biological_systems slugs; ask_vet_first
-- is true for anything with real interaction risk. natural_remedies.kind now
-- also uses topical|physical|environment|behavior|lifestyle (0013 had only
-- food); contraindications/medication_interactions item_kind adds 'remedy'.
--
-- >>> generated from live DB (do not hand-edit below)
insert into public.herb_profiles (slug, name, benefit, systems, dog_safety, cat_safety, evidence_grade, ask_vet_first, thermal_nature, flavor, tcm_pattern, source) values
  ('aloe_inner', 'Aloe vera (inner leaf gel only)', 'May help soothe skin topically; inner gel only, never whole-leaf latex.', '["skin", "gut"]', 'caution', 'caution', 'D', 't', 'cooling', 'Bitter', 'Clears Heat; moistens', 'Whole-leaf/latex aloe is on the ASPCA toxic list; inner gel is generally tolerated.'),
  ('ashwagandha', 'Ashwagandha (withania)', 'Adaptogen that may help support stress resilience and healthy cortisol response.', '["behavior", "immune"]', 'caution', 'caution', 'C', 't', 'warming', 'Bitter', 'Tonifies Kidney Yang; calms the Shen', 'Ayurvedic adaptogen; small canine stress studies.'),
  ('astragalus', 'Astragalus root', 'Adaptogen that may help support immune resilience and kidney function.', '["immune", "renal"]', 'caution', 'caution', 'C', 't', 'warming', 'Sweet', 'Tonifies Qi; raises Yang; supports Spleen and Lung', 'TCVM tonic; limited veterinary data.'),
  ('boswellia', 'Boswellia (frankincense resin)', 'May help support joint comfort and mobility in osteoarthritis.', '["msk"]', 'caution', 'caution', 'B', 't', 'warming', 'Bitter', 'Moves Blood; relieves stagnation pain', 'Canine OA trial (Reichling 2004) showed improvement in clinical signs.'),
  ('calendula', 'Calendula (pot marigold)', 'Topical wash or salve that may help support minor skin irritation and wound healing.', '["skin"]', 'safe', 'caution', 'C', 'f', 'neutral', 'Bitter', 'Clears Heat and toxins from the skin', 'Traditional vulnerary; topical use is well tolerated in dogs.'),
  ('cats_claw', 'Cat''s claw (Uncaria tomentosa)', 'May help support immune and joint health.', '["immune", "msk"]', 'caution', 'caution', 'D', 't', 'cooling', 'Bitter', 'Clears Heat; dispels Wind-Damp', 'Traditional Amazonian use; avoid in autoimmune disease and pregnancy.'),
  ('chamomile', 'Chamomile', 'May help support calm and mild digestive comfort.', '["behavior", "gut"]', 'caution', 'caution', 'D', 't', 'cooling', 'Bitter / sweet', 'Calms the Liver; clears mild Heat', 'Traditional calming use.'),
  ('cranberry_herb', 'Cranberry (whole fruit extract)', 'May help reduce bacterial adhesion in the urinary tract.', '["renal"]', 'caution', 'caution', 'C', 't', 'cooling', 'Sour', 'Clears Damp-Heat from the Bladder', 'Canine proanthocyanidin studies show reduced E. coli adherence.'),
  ('dandelion', 'Dandelion (leaf & root)', 'Leaf is a gentle potassium-sparing diuretic; root may support liver and digestion.', '["hepatic", "renal", "gut"]', 'caution', 'caution', 'D', 't', 'cooling', 'Bitter', 'Clears Heat; drains Damp; supports Liver', 'Traditional Western herbalism; avoid with bile-duct obstruction.'),
  ('devils_claw', 'Devil''s claw', 'May help support joint comfort; bitter tonic for appetite.', '["msk", "gut"]', 'caution', 'avoid', 'C', 't', 'cooling', 'Bitter', 'Clears Heat; relieves Bi pain', 'Traditional anti-inflammatory; avoid with GI ulcers, pregnancy, and in cats.'),
  ('echinacea', 'Echinacea', 'May help support immune response during short-term respiratory or skin challenges.', '["immune"]', 'caution', 'caution', 'C', 't', 'cooling', 'Pungent', 'Clears Heat and toxins', 'Small canine URI study; avoid in autoimmune disease.'),
  ('ginger', 'Ginger root', 'May help ease nausea and motion sickness; mild digestive warming support.', '["gut"]', 'caution', 'caution', 'C', 't', 'warming', 'Pungent', 'Warms the Middle; descends Stomach Qi', 'Traditional antiemetic use; small canine motion-sickness data.'),
  ('hawthorn', 'Hawthorn berry', 'May help support cardiac function and circulation in early heart disease.', '["metabolic"]', 'caution', 'caution', 'C', 't', 'warming', 'Sour', 'Moves Blood; reduces food stagnation', 'Traditional cardiotonic; potentiates digoxin.'),
  ('licorice_root', 'Licorice root (glycyrrhiza)', 'May help support inflamed mucosa and adrenal balance; short courses only.', '["gut", "immune", "skin"]', 'caution', 'caution', 'C', 't', 'neutral', 'Sweet', 'Tonifies Spleen Qi; harmonizes formulas', 'Traditional use; glycyrrhizin can raise blood pressure and lower potassium with prolonged use.'),
  ('lions_mane', 'Lion''s mane mushroom', 'May help support cognitive health in senior pets.', '["behavior"]', 'caution', 'caution', 'D', 't', 'neutral', 'Sweet', 'Tonifies Spleen; nourishes the Brain', 'NGF-related preclinical data; no controlled pet trials.'),
  ('marshmallow_root', 'Marshmallow root', 'Demulcent that may help soothe irritated gut and urinary linings.', '["gut", "renal"]', 'caution', 'caution', 'D', 't', 'cooling', 'Sweet', 'Moistens Dryness; soothes Stomach and Bladder', 'Traditional demulcent use (AHVMA herbal references).'),
  ('milk_thistle', 'Milk thistle (silymarin)', 'May help support the liver during recovery.', '["hepatic"]', 'caution', 'caution', 'C', 't', 'cooling', 'Bitter', 'Clears Damp-Heat; supports the Liver', 'Hepatoprotective traditional + emerging data.'),
  ('nettle', 'Stinging nettle leaf', 'May help support seasonal allergy comfort and provide trace minerals.', '["skin", "immune"]', 'caution', 'caution', 'D', 't', 'cooling', 'Bitter', 'Clears Wind-Heat from the skin', 'Traditional antihistamine-like use.'),
  ('oregon_grape', 'Oregon grape root (berberine)', 'Antimicrobial bitter that may help support gut and skin infections.', '["gut", "skin"]', 'caution', 'avoid', 'C', 't', 'cooling', 'Bitter', 'Clears Damp-Heat', 'Berberine-containing herb; avoid in pregnancy, liver disease, and cats.'),
  ('passionflower', 'Passionflower', 'Gentle nervine that may help support relaxation.', '["behavior"]', 'caution', 'caution', 'D', 't', 'cooling', 'Bitter', 'Calms the Shen; clears Heart Heat', 'Traditional nervine use.'),
  ('peppermint', 'Peppermint leaf', 'May help support gas and mild digestive discomfort in dogs.', '["gut"]', 'caution', 'avoid', 'D', 't', 'cooling', 'Pungent', 'Spreads Liver Qi; clears Wind-Heat', 'Essential oil is toxic to cats; use only dilute leaf tea in dogs.'),
  ('reishi', 'Reishi mushroom', 'May help support immune balance and calm.', '["immune", "behavior"]', 'caution', 'caution', 'D', 't', 'neutral', 'Bitter', 'Tonifies Qi; calms the Shen', 'Traditional tonic; limited veterinary data.'),
  ('skullcap', 'Skullcap (Scutellaria lateriflora)', 'Nervine that may help support calm and nervous tension.', '["behavior"]', 'caution', 'caution', 'D', 't', 'cooling', 'Bitter', 'Clears Heat; calms Liver Wind', 'Traditional use; confirm species (American, not Chinese Baikal) on labels.'),
  ('slippery_elm', 'Slippery elm bark', 'May help soothe the digestive tract (demulcent).', '["gut"]', 'caution', 'caution', 'C', 't', 'neutral', 'Sweet', 'Moistens and soothes the Stomach', 'Traditional demulcent use.'),
  ('turkey_tail', 'Turkey tail mushroom (Coriolus / PSP)', 'Immune-modulating mushroom; may help support quality of life alongside cancer care.', '["immune"]', 'caution', 'caution', 'B', 't', 'neutral', 'Sweet', 'Tonifies Qi; clears Damp', 'Penn Vet hemangiosarcoma pilot (Brown & Reetz 2012) improved survival with high-dose PSP.'),
  ('turmeric', 'Turmeric / curcumin', 'May help support balanced inflammation in some dogs.', '["msk", "immune"]', 'caution', 'avoid', 'C', 't', 'warming', 'Bitter / pungent', 'Moves Blood and Qi; warms', 'Anti-inflammatory research.'),
  ('valerian', 'Valerian root', 'May help support calm during situational stress (travel, fireworks).', '["behavior"]', 'caution', 'caution', 'C', 't', 'warming', 'Bitter', 'Calms the Shen', 'Traditional sedative; paradoxical excitement possible.'),
  ('yucca', 'Yucca schidigera', 'Saponin-rich herb that may help support joint comfort and reduce stool odor.', '["msk", "gut"]', 'caution', 'caution', 'C', 't', 'neutral', 'Bitter', 'Moves Qi; relieves Bi', 'Common feed additive; intermittent use to avoid GI upset.'),
  ('yunnan_baiyao', 'Yunnan Baiyao', 'TCVM formula that may help support clotting in bleeding conditions.', '["immune", "metabolic"]', 'caution', 'caution', 'C', 't', 'warming', 'Pungent', 'Stops bleeding; moves Blood', 'Used in canine hemangiosarcoma protocols; short courses only, under vet direction.')
on conflict (slug) do nothing;

insert into public.natural_remedies (slug, name, kind, systems, benefit, evidence_grade, ask_vet_first, source) values
  ('blueberries', 'Fresh blueberries', 'food', '["immune", "behavior"]', 'Antioxidant treat; small canine cognition study on antioxidant-rich diets.', 'C', 'f', 'Antioxidant-diet cognition data (Milgram).'),
  ('boiled_chicken', 'Plain boiled skinless chicken', 'food', '["gut"]', 'Lean protein for bland recovery diets (2-3 days, then transition back).', 'C', 'f', 'Bland-diet practice.'),
  ('bone_broth', 'Plain bone broth', 'food', '["gut", "msk"]', 'Hydrating and palatable; may help support intake during recovery.', 'D', 'f', 'Supportive-nutrition practice.'),
  ('carrots', 'Raw or steamed carrot', 'food', '["dental", "metabolic"]', 'Low-calorie crunchy treat; mild dental abrasion benefit.', 'D', 'f', 'Treat guidance.'),
  ('coconut_oil', 'Virgin coconut oil (small amounts)', 'food', '["skin"]', 'May help support coat shine; high in saturated fat — avoid with pancreatitis.', 'D', 't', 'Anecdotal; MCT content.'),
  ('cold_compress', 'Cold compress', 'physical', '["msk"]', 'May help reduce swelling after acute strain (first 48h).', 'C', 'f', 'Rehab guidance.'),
  ('dental_brushing', 'Daily tooth brushing', 'physical', '["dental"]', 'Gold-standard home plaque control.', 'A', 'f', 'VOHC / AVDC guidance.'),
  ('eggs', 'Cooked egg', 'food', '["skin", "metabolic"]', 'Highly digestible complete protein; may help support coat quality.', 'D', 'f', 'Nutritional practice.'),
  ('elevated_bowl', 'Elevated feeding bowl (giant breeds)', 'environment', '["gut"]', 'Sometimes used for megaesophagus; evidence links raised bowls to higher GDV risk in giant breeds — ask vet.', 'C', 't', 'Glickman GDV study.'),
  ('epsom_soak', 'Epsom salt paw soak', 'topical', '["skin", "msk"]', 'May help soothe sore or irritated paws; do not allow drinking.', 'D', 'f', 'Supportive care practice.'),
  ('goats_milk', 'Raw or fermented goat''s milk', 'food', '["gut"]', 'Palatable hydration and probiotic source for some pets; raw products carry pathogen risk.', 'D', 't', 'Raw-product caution (FDA).'),
  ('green_beans', 'Plain green beans', 'food', '["metabolic"]', 'Low-calorie filler that may help with weight management.', 'C', 'f', 'Weight-management feeding practice.'),
  ('humidifier', 'Room humidifier / steam', 'environment', '["immune"]', 'May help ease congestion during upper-respiratory infections (especially cats).', 'D', 'f', 'Feline URI supportive care.'),
  ('hydrotherapy', 'Swimming / underwater treadmill', 'physical', '["msk"]', 'Low-impact conditioning for arthritis and post-surgical recovery.', 'B', 't', 'Canine rehab literature.'),
  ('leash_rest', 'Strict leash rest', 'physical', '["msk"]', 'Foundational for soft-tissue and joint recovery.', 'B', 'f', 'Orthopedic rehab guidance.'),
  ('oatmeal_bath', 'Colloidal oatmeal bath', 'topical', '["skin"]', 'May help soothe itchy, irritated skin.', 'C', 'f', 'Dermatology supportive care.'),
  ('pheromone_diffuser', 'Synthetic pheromone diffuser (DAP / Feliway)', 'environment', '["behavior"]', 'May help reduce situational anxiety.', 'B', 'f', 'Multiple controlled trials with mixed but generally positive results.'),
  ('plain_rice', 'Plain boiled white rice', 'food', '["gut"]', 'Easily digested carbohydrate for short bland-diet recovery.', 'C', 'f', 'Bland-diet practice (VCA).'),
  ('plain_yogurt', 'Plain unsweetened yogurt (small amounts)', 'food', '["gut"]', 'Live-culture food that may help support gut flora in lactose-tolerant pets.', 'D', 'f', 'Avoid xylitol-sweetened or flavored products.'),
  ('pumpkin', 'Plain pumpkin (soluble fiber)', 'food', '["gut"]', 'May help support stool consistency.', 'C', 'f', 'Soluble-fiber guidance.'),
  ('puzzle_feeder', 'Puzzle or slow feeder', 'behavior', '["behavior", "gut"]', 'Slows eating, reduces bloat risk and boredom.', 'C', 'f', 'Behavior enrichment guidance.'),
  ('saline_eye_rinse', 'Sterile saline eye rinse', 'topical', '["skin"]', 'Flushes mild debris or discharge; not for injuries or ulcers.', 'C', 'f', 'First-aid guidance.'),
  ('sardines', 'Canned sardines in water (no salt)', 'food', '["skin", "msk"]', 'Whole-food omega-3 source for skin, coat and joint support.', 'C', 'f', 'Omega-3 dietary guidance.'),
  ('sweet_potato', 'Cooked sweet potato', 'food', '["gut"]', 'Fiber and beta-carotene; may help support stool consistency.', 'D', 'f', 'Fiber guidance.'),
  ('warm_compress', 'Warm compress', 'physical', '["msk", "skin"]', 'May help ease chronic joint stiffness and encourage drainage of minor abscesses.', 'D', 'f', 'Rehab guidance.'),
  ('weight_loss_plan', 'Structured weight reduction', 'lifestyle', '["msk", "metabolic"]', 'Strongest single lever for OA comfort in overweight pets.', 'A', 't', 'Multiple canine OA weight-loss trials.'),
  ('white_fish', 'Plain cooked white fish', 'food', '["gut", "renal"]', 'A gentle lean protein for bland recovery diets.', 'C', 'f', 'Bland-diet practice.')
on conflict (slug) do nothing;

insert into public.supplement_ingredients (slug, name, benefit, systems, dog_safety, cat_safety, evidence_grade, ask_vet_first, source) values
  ('alpha_casozepine', 'Alpha-casozepine (milk protein hydrolysate)', 'May help support calm in stressful situations.', '["behavior"]', 'safe', 'safe', 'B', 'f', 'Feline and canine placebo-controlled trials (Zylkene).'),
  ('aluminum_free_phos_binder', 'Phosphate binder (calcium/chitosan-based)', 'May help control phosphorus in chronic kidney disease.', '["renal"]', 'caution', 'caution', 'B', 't', 'IRIS CKD guidelines; vet-directed.'),
  ('beta_glucan', 'Beta-glucans (yeast / mushroom)', 'May help support immune balance.', '["immune"]', 'safe', 'safe', 'C', 'f', 'Canine immune-marker studies.'),
  ('biotin', 'Biotin', 'B-vitamin that may help support coat and nail quality.', '["skin"]', 'safe', 'safe', 'D', 'f', 'Limited data.'),
  ('cbd', 'Cannabidiol (hemp-derived CBD)', 'May help support joint comfort and situational calm; legal status varies.', '["msk", "behavior"]', 'caution', 'caution', 'B', 't', 'Cornell canine OA trial (Gamble 2018); THC-free products only.'),
  ('chlorophyll', 'Chlorophyll', 'May help reduce breath and body odor.', '["dental"]', 'safe', 'safe', 'D', 'f', 'Anecdotal.'),
  ('choline', 'Choline / lecithin', 'May help support liver fat metabolism and cognition.', '["hepatic", "behavior"]', 'safe', 'safe', 'D', 'f', 'Limited data.'),
  ('chondroitin', 'Chondroitin sulfate', 'May help support cartilage; usually paired with glucosamine.', '["msk"]', 'safe', 'safe', 'C', 'f', 'Mixed canine OA trials.'),
  ('colostrum', 'Bovine colostrum', 'May help support gut lining and immune function.', '["gut", "immune"]', 'safe', 'safe', 'C', 'f', 'Canine gut-health and immune-response studies.'),
  ('coq10', 'Coenzyme Q10', 'Antioxidant that may help support heart and gum health.', '["metabolic", "dental"]', 'safe', 'safe', 'C', 'f', 'Cardiac supportive use.'),
  ('cranberry', 'Cranberry extract', 'May help support lower-urinary-tract health.', '["renal"]', 'safe', 'caution', 'C', 'f', 'Urinary-adjunct literature.'),
  ('d_mannose', 'D-mannose', 'May help reduce E. coli adhesion in the urinary tract.', '["renal"]', 'safe', 'safe', 'D', 't', 'Human UTI data; extrapolated.'),
  ('digestive_enzymes', 'Digestive enzymes', 'May help support digestion under veterinary guidance.', '["hepatic", "gut"]', 'caution', 'caution', 'C', 't', 'Used for exocrine pancreatic insufficiency.'),
  ('fos_prebiotic', 'Prebiotic fiber (FOS / inulin)', 'Feeds beneficial gut bacteria.', '["gut", "immune"]', 'safe', 'safe', 'C', 'f', 'Companion-animal microbiome studies.'),
  ('glucosamine', 'Glucosamine + chondroitin', 'May help support joint comfort and mobility.', '["msk"]', 'safe', 'safe', 'B', 'f', 'Osteoarthritis literature.'),
  ('green_lipped_mussel', 'Green-lipped mussel (Perna canaliculus)', 'Omega-3 and glycosaminoglycan source; may help support joint comfort.', '["msk"]', 'safe', 'safe', 'B', 'f', 'Several canine OA trials show benefit.'),
  ('l_carnitine', 'L-carnitine', 'May help support fat metabolism and heart muscle.', '["metabolic"]', 'safe', 'safe', 'C', 'f', 'Boxer DCM and weight-loss diet data.'),
  ('l_lysine', 'L-lysine', 'Historically used for feline herpesvirus; recent reviews show little benefit.', '["immune"]', 'safe', 'safe', 'C', 'f', 'Bol & Bunnik 2015 systematic review: no clear benefit.'),
  ('l_theanine', 'Calming nutraceutical (L-theanine)', 'May help support calm behavior during stress.', '["behavior"]', 'safe', 'caution', 'C', 'f', 'Behavioral nutraceutical studies.'),
  ('l_tryptophan', 'L-tryptophan', 'Serotonin precursor that may help support calm behavior.', '["behavior"]', 'caution', 'caution', 'C', 't', 'Canine anxiety diet studies.'),
  ('lactoferrin', 'Lactoferrin', 'May help support oral health in cats with stomatitis.', '["dental", "immune"]', 'safe', 'safe', 'C', 't', 'Feline stomatitis topical study.'),
  ('mct_oil', 'MCT oil', 'Alternative brain fuel that may help support senior cognition and seizure control.', '["behavior", "metabolic"]', 'caution', 'caution', 'B', 't', 'Canine cognition and epilepsy diet trials (Pan 2010; Law 2015).'),
  ('melatonin', 'Melatonin', 'May help support sleep-wake cycles and noise phobia; used in canine alopecia X.', '["behavior", "skin"]', 'caution', 'caution', 'C', 't', 'Check for xylitol in human products.'),
  ('msm', 'MSM (methylsulfonylmethane)', 'Sulfur donor that may help support joint and connective tissue.', '["msk", "skin"]', 'safe', 'safe', 'D', 'f', 'Limited data.'),
  ('nac', 'N-acetylcysteine (NAC)', 'Glutathione precursor; used for acetaminophen toxicity and respiratory mucus.', '["hepatic", "immune"]', 'caution', 'caution', 'B', 't', 'Vet-directed antidote and supportive use.'),
  ('omega3', 'Omega-3 fish oil (EPA/DHA)', 'May help support skin barrier, joints, and balanced inflammation.', '["skin", "immune", "msk", "renal"]', 'safe', 'safe', 'B', 'f', 'Veterinary nutrition reviews.'),
  ('phosphatidylserine', 'Phosphatidylserine', 'May help support cognition in senior dogs.', '["behavior"]', 'safe', 'safe', 'C', 'f', 'Canine cognitive dysfunction supplement trials.'),
  ('potassium_citrate', 'Potassium citrate', 'Alkalinizes urine; used in calcium-oxalate stone prevention.', '["renal"]', 'caution', 'caution', 'B', 't', 'Vet-directed only; urine pH monitoring needed.'),
  ('probiotic', 'Multi-strain probiotic', 'May help support a balanced gut microbiome.', '["gut", "immune"]', 'safe', 'safe', 'B', 'f', 'Veterinary probiotic trials.'),
  ('probiotic_e_faecium', 'Enterococcus faecium SF68', 'Well-studied probiotic strain for dogs and cats.', '["gut", "immune"]', 'safe', 'safe', 'B', 'f', 'Feline and canine diarrhea trials (FortiFlora).'),
  ('psyllium', 'Psyllium husk', 'Soluble fiber that may help support both constipation and large-bowel diarrhea.', '["gut"]', 'safe', 'safe', 'B', 'f', 'Fiber-responsive diarrhea data; give with water.'),
  ('quercetin', 'Quercetin', 'Plant flavonoid sometimes called "nature''s Benadryl"; may help support allergy comfort.', '["skin", "immune"]', 'caution', 'caution', 'D', 't', 'No controlled pet trials.'),
  ('s_boulardii', 'Saccharomyces boulardii', 'Probiotic yeast that may help support the gut during antibiotic use and chronic enteropathy.', '["gut"]', 'safe', 'safe', 'B', 'f', 'Canine chronic enteropathy RCT (D''Angelo 2018).'),
  ('sam_e', 'SAMe (S-adenosylmethionine)', 'May help support liver function and cognition.', '["hepatic", "behavior"]', 'safe', 'safe', 'B', 't', 'Canine hepatopathy and cognitive dysfunction data.'),
  ('silybin_phos', 'Silybin-phosphatidylcholine complex', 'Bioavailable milk-thistle fraction that may help support liver cells.', '["hepatic"]', 'safe', 'safe', 'B', 't', 'Canine pharmacokinetic and hepatopathy data.'),
  ('spirulina', 'Spirulina', 'Nutrient-dense algae that may help support immune function; source quality matters (microcystin risk).', '["immune"]', 'caution', 'caution', 'D', 't', 'Contamination risk in low-quality products.'),
  ('taurine', 'Taurine', 'Essential amino acid for cats; may help support heart function in some dog breeds.', '["metabolic"]', 'safe', 'safe', 'A', 't', 'Feline DCM/retinal deficiency data; canine diet-associated DCM.'),
  ('uc2_collagen', 'Undenatured type II collagen (UC-II)', 'May help support joint mobility via oral tolerance.', '["msk"]', 'safe', 'caution', 'B', 'f', 'Canine trials (Gupta 2012) improved mobility scores.'),
  ('vitamin_b12', 'Cobalamin (vitamin B12)', 'Frequently deficient in chronic GI disease; supports red cells and nerves.', '["gut", "metabolic"]', 'safe', 'safe', 'A', 't', 'Oral cobalamin proven effective in dogs and cats with hypocobalaminemia.'),
  ('vitamin_e', 'Vitamin E', 'Antioxidant that may help support skin and immune function.', '["skin", "immune"]', 'safe', 'safe', 'C', 'f', 'Often paired with omega-3.'),
  ('zinc', 'Zinc (chelated)', 'Supports skin and immune health; specific therapy for zinc-responsive dermatosis.', '["skin", "immune"]', 'caution', 'caution', 'B', 't', 'Toxic in excess; breed-specific dermatosis data.')
on conflict (slug) do nothing;

insert into public.contraindications (item_slug, item_kind, contraindication)
select v.item_slug, v.item_kind, v.contraindication from (values
  ('aloe_inner', 'herb', 'Whole-leaf or latex aloe causes vomiting, diarrhea, and lethargy.'),
  ('ashwagandha', 'herb', 'Avoid with thyroid medication and in pregnancy; may potentiate sedatives.'),
  ('astragalus', 'herb', 'Avoid in acute infection with fever and in autoimmune disease.'),
  ('boswellia', 'herb', 'May cause GI upset; use cautiously with NSAIDs.'),
  ('cats_claw', 'herb', 'Avoid in autoimmune disease, pregnancy, and with immunosuppressants.'),
  ('cbd', 'supplement', 'Avoid products containing THC; may elevate ALP; use with caution alongside other liver-metabolized drugs.'),
  ('chamomile', 'herb', 'Ragweed-family allergy'),
  ('coconut_oil', 'remedy', 'Avoid with pancreatitis, hyperlipidemia, or obesity.'),
  ('cranberry', 'supplement', 'History of calcium-oxalate stones'),
  ('dandelion', 'herb', 'Avoid with bile-duct obstruction or gallstones.'),
  ('devils_claw', 'herb', 'Avoid with GI ulcers, gallstones, diabetes, pregnancy, and in cats.'),
  ('digestive_enzymes', 'supplement', 'Do NOT use during an acute pancreatitis flare'),
  ('echinacea', 'herb', 'Avoid in autoimmune disease and with immunosuppressants; limit to 8 weeks.'),
  ('elevated_bowl', 'remedy', 'Associated with increased GDV risk in large and giant breeds.'),
  ('epsom_soak', 'remedy', 'Do not allow pet to drink the solution; avoid on open wounds.'),
  ('ginger', 'herb', 'Avoid with gallstones.'),
  ('ginger', 'herb', 'Stop before surgery and avoid with anticoagulants or bleeding disorders.'),
  ('goats_milk', 'remedy', 'Raw dairy carries Salmonella/Listeria/E. coli risk; avoid in immunocompromised households.'),
  ('green_lipped_mussel', 'supplement', 'Avoid in pets with shellfish allergy.'),
  ('hawthorn', 'herb', 'Do not combine with cardiac glycosides or beta-blockers without veterinary direction.'),
  ('l_tryptophan', 'supplement', 'Avoid with SSRIs, MAOIs, or trazodone (serotonin syndrome risk).'),
  ('licorice_root', 'herb', 'Avoid in pregnancy.'),
  ('licorice_root', 'herb', 'Avoid with heart disease, hypertension, kidney disease, or hypokalemia; limit courses to 2-3 weeks.'),
  ('mct_oil', 'supplement', 'Avoid with pancreatitis or hyperlipidemia; introduce gradually.'),
  ('melatonin', 'supplement', 'Never use human products containing xylitol; avoid in pregnancy and with diabetes.'),
  ('milk_thistle', 'herb', 'Pregnancy'),
  ('nac', 'supplement', 'May cause vomiting; do not use for cats without veterinary direction.'),
  ('omega3', 'supplement', 'Known bleeding disorder'),
  ('omega3', 'supplement', 'Scheduled surgery'),
  ('oregon_grape', 'herb', 'Avoid in pregnancy, neonates, liver disease, and in cats.'),
  ('peppermint', 'herb', 'Essential oil is toxic to cats and small dogs; never apply undiluted.'),
  ('plain_yogurt', 'remedy', 'Avoid in lactose-intolerant pets and any product containing xylitol.'),
  ('potassium_citrate', 'supplement', 'Avoid in hyperkalemia, kidney failure, and with potassium-sparing drugs.'),
  ('psyllium', 'supplement', 'Always give with adequate water; avoid with GI obstruction.'),
  ('s_boulardii', 'supplement', 'Avoid in severely immunocompromised pets (rare fungemia risk).'),
  ('sam_e', 'supplement', 'Give on an empty stomach; avoid with serotonergic drugs.'),
  ('spirulina', 'supplement', 'Choose products tested for microcystins and heavy metals.'),
  ('taurine', 'supplement', 'Not a substitute for a complete diet; supplement only alongside veterinary diagnosis.'),
  ('turkey_tail', 'herb', 'Discuss with oncologist if pet is on chemotherapy.'),
  ('turmeric', 'herb', 'Bleeding disorder'),
  ('turmeric', 'herb', 'Gallbladder obstruction'),
  ('valerian', 'herb', 'Stop 2 weeks before anesthesia; avoid with sedatives.'),
  ('yucca', 'herb', 'Continuous long-term use may irritate the GI tract; cycle 5 days on / 2 off.'),
  ('yunnan_baiyao', 'herb', 'Contains aconite in some formulations; short courses only under veterinary direction.'),
  ('zinc', 'supplement', 'Toxic in excess (vomiting, hemolysis); dose by veterinary direction.')
) v(item_slug, item_kind, contraindication)
where not exists (select 1 from public.contraindications c where c.item_slug = v.item_slug and c.item_kind = v.item_kind and c.contraindication = v.contraindication);

insert into public.medication_interactions (item_slug, item_kind, drug_class, note)
select v.item_slug, v.item_kind, v.drug_class, v.note from (values
  ('aluminum_free_phos_binder', 'supplement', 'Oral medications', 'Binds and reduces absorption; separate dosing.'),
  ('ashwagandha', 'herb', 'Sedatives / behavior meds', 'Additive sedation.'),
  ('ashwagandha', 'herb', 'Thyroid medication', 'May raise thyroid hormone levels.'),
  ('astragalus', 'herb', 'Immunosuppressants', 'May counteract effect.'),
  ('boswellia', 'herb', 'NSAIDs', 'Additive GI-irritation risk.'),
  ('cbd', 'supplement', 'Liver-metabolized drugs', 'CYP450 inhibition may raise drug levels (phenobarbital, NSAIDs).'),
  ('cbd', 'supplement', 'Sedatives / behavior meds', 'Additive sedation.'),
  ('coq10', 'supplement', 'Anticoagulants', 'May reduce warfarin effect.'),
  ('cranberry_herb', 'herb', 'Anticoagulants', 'Possible warfarin potentiation.'),
  ('dandelion', 'herb', 'Diuretics', 'Additive diuretic and potassium effects.'),
  ('devils_claw', 'herb', 'Anticoagulants', 'Increased bleeding risk.'),
  ('devils_claw', 'herb', 'NSAIDs', 'Additive GI ulcer risk.'),
  ('echinacea', 'herb', 'Immunosuppressants', 'May counteract cyclosporine or steroids.'),
  ('ginger', 'herb', 'Anticoagulants', 'Additive antiplatelet effect.'),
  ('green_lipped_mussel', 'supplement', 'Anticoagulants', 'Additive antiplatelet effect from omega-3s.'),
  ('hawthorn', 'herb', 'Beta-blockers / ACE inhibitors', 'Additive hypotension.'),
  ('hawthorn', 'herb', 'Cardiac glycosides', 'Potentiates digoxin.'),
  ('l_theanine', 'supplement', 'Sedatives / behavior meds', 'Additive sedation — confirm dose.'),
  ('l_tryptophan', 'supplement', 'SSRIs / MAOIs / trazodone', 'Serotonin syndrome risk.'),
  ('licorice_root', 'herb', 'Corticosteroids', 'Prolongs steroid activity; potassium loss.'),
  ('licorice_root', 'herb', 'Diuretics', 'Additive hypokalemia.'),
  ('mct_oil', 'supplement', 'Anticonvulsants', 'Intended synergy; dose adjustments may be needed.'),
  ('melatonin', 'supplement', 'Corticosteroids', 'May blunt steroid effect.'),
  ('melatonin', 'supplement', 'Sedatives / benzodiazepines', 'Additive sedation.'),
  ('milk_thistle', 'herb', 'Liver-metabolized drugs', 'May alter drug metabolism — time separately.'),
  ('nac', 'supplement', 'Nitroglycerin', 'Additive hypotension.'),
  ('omega3', 'supplement', 'Anticoagulants', 'Additive bleeding risk — confirm with your vet.'),
  ('omega3', 'supplement', 'High-dose NSAIDs', 'Monitor for GI/bleeding effects.'),
  ('oregon_grape', 'herb', 'Liver-metabolized drugs', 'Berberine inhibits CYP enzymes.'),
  ('passionflower', 'herb', 'Sedatives / behavior meds', 'Additive CNS depression.'),
  ('potassium_citrate', 'supplement', 'ACE inhibitors / spironolactone', 'Hyperkalemia risk.'),
  ('probiotic_e_faecium', 'supplement', 'Antibiotics', 'Separate by 2 hours for best survival.'),
  ('psyllium', 'supplement', 'Oral medications', 'May reduce absorption; separate by 2 hours.'),
  ('s_boulardii', 'supplement', 'Antifungals', 'Antifungals inactivate the yeast; separate dosing.'),
  ('sam_e', 'supplement', 'SSRIs / tramadol / trazodone', 'Serotonin syndrome risk.'),
  ('skullcap', 'herb', 'Sedatives / behavior meds', 'Additive CNS depression.'),
  ('slippery_elm', 'herb', 'Oral medications', 'Can reduce absorption — give 1–2 hours apart.'),
  ('turkey_tail', 'herb', 'Chemotherapy', 'Possible immune-modulation interaction; discuss with oncologist.'),
  ('turmeric', 'herb', 'Anticoagulants', 'May increase bleeding risk.'),
  ('valerian', 'herb', 'Sedatives / anesthetics', 'Additive CNS depression.'),
  ('vitamin_e', 'supplement', 'Anticoagulants', 'High doses increase bleeding risk.'),
  ('yunnan_baiyao', 'herb', 'Anticoagulants', 'Opposing effects; unpredictable.'),
  ('zinc', 'supplement', 'Antibiotics (fluoroquinolones, tetracyclines)', 'Reduces antibiotic absorption; separate by 2 hours.')
) v(item_slug, item_kind, drug_class, note)
where not exists (select 1 from public.medication_interactions m where m.item_slug = v.item_slug and m.item_kind = v.item_kind and m.drug_class = v.drug_class and m.note is not distinct from v.note);
