-- 0028_marketplace_supplements_seed.sql
-- 30 real supplement products from the 2026-09-07 brand & affiliate research
-- (34 brands profiled; NASC member list fetched the same day). Ported
-- byte-for-byte from the research database via server-side SQL generation.
--
-- evidence_status: brand_claim = data from brand/authoritative pages;
-- crowdsourced_unverified = thin transparency (PetTides BPC-157, Wizard
-- Sciences) — kept low-scored pending Brandon's keep/hide/drop decision.
-- Runs after 0026 (columns + demo flagging of the 12 "(example)" rows).
--
-- >>> generated from live DB (do not hand-edit below)
insert into public.marketplace_products (slug, category, name, species, evidence, transparency, ingredient_quality, lab_tested, reported_outcomes, fit_tags, blurb, brand, product_url, affiliate_program, affiliate_url, affiliate_commission, nasc_seal, source_notes, evidence_status) values
  ('animalessentials_enzyme_probiotic', 'enzymes', 'Animal Essentials Plant Enzymes & Probiotics', 'both', 'C', '4', '4', 't', '3', '{gut,enzymes,probiotic}', 'Herbalist-founded brand; NASC Quality Seal; wholesale + in-house affiliate.', 'Animal Essentials', 'https://animalessentials.com', 'In-house (BixGrow)', 'https://animalessentials.com/pages/become-an-affiliate', 'not published', 't', 'Brand affiliate page', 'brand_claim'),
  ('ellevet_calm_oil', 'supplements', 'ElleVet Calm & Comfort Oil', 'both', 'B', '5', '4', 't', '4', '{calming,anxiety,cbd}', 'Situational-stress CBD+CBDA oil for dogs and cats.', 'ElleVet Sciences', 'https://www.ellevetsciences.com', 'CJ Affiliate', 'https://www.ellevetsciences.com/affilate-program/', 'up to 30%, 30-day cookie', 't', 'Brand affiliate page', 'brand_claim'),
  ('ellevet_mobility_chews', 'supplements', 'ElleVet Mobility Chews (CBD+CBDA)', 'dog', 'B', '5', '4', 't', '4', '{joint,mobility,cbd,senior}', 'Cornell-trialed CBD+CBDA for osteoarthritis comfort; NASC Quality Seal.', 'ElleVet Sciences', 'https://www.ellevetsciences.com', 'CJ Affiliate', 'https://www.ellevetsciences.com/affilate-program/', 'up to 30%, 30-day cookie', 't', 'Cornell OA trial; brand affiliate page', 'brand_claim'),
  ('fera_fish_oil', 'omega3', 'Fera Pets Fish Oil', 'both', 'B', '5', '4', 't', '4', '{skin,coat,joint,omega-3}', 'Omega-3 fish oil with published COAs.', 'Fera Pets', 'https://www.ferapets.com', 'Ambassador program (brand) / Mopubi network', 'https://www.ferapets.com/pages/ambassadorprogram', '8%, 30-day cookie (network listing, unverified)', 't', 'Network listing rate unverified with brand', 'brand_claim'),
  ('fera_probiotics', 'probiotics', 'Fera Pets Probiotics with Prebiotics', 'both', 'C', '5', '4', 't', '4', '{gut,probiotic,digestive}', 'DVM-founded; public COA lookup per batch; NASC Quality Seal.', 'Fera Pets', 'https://www.ferapets.com', 'Ambassador program (brand) / Mopubi network', 'https://www.ferapets.com/pages/ambassadorprogram', '8%, 30-day cookie (network listing, unverified)', 't', 'Network listing rate unverified with brand', 'brand_claim'),
  ('fourleafrover_protect', 'probiotics', 'Four Leaf Rover Protect (soil-based probiotic)', 'dog', 'C', '5', '5', 't', '4', '{gut,probiotic,detox}', 'Vet-formulated soil-based probiotic; third-party tested for heavy metals and pesticides; NASC Quality Seal.', 'Four Leaf Rover', 'https://fourleafrover.com', 'Impact', 'https://fourleafrover.com/four-leaf-rover-affiliate-sign-up', 'not published by brand (5–15% per directories), 30-day cookie', 't', 'Brand affiliate page', 'brand_claim'),
  ('fourleafrover_safe_sea', 'omega3', 'Four Leaf Rover Safe-Sea (green-lipped mussel oil)', 'dog', 'B', '5', '5', 't', '4', '{joint,skin,omega-3,glm}', 'Green-lipped mussel omega-3 alternative to fish oil.', 'Four Leaf Rover', 'https://fourleafrover.com', 'Impact', 'https://fourleafrover.com/four-leaf-rover-affiliate-sign-up', 'not published by brand, 30-day cookie', 't', 'Brand affiliate page', 'brand_claim'),
  ('herbsmith_microflora', 'probiotics', 'Herbsmith Microflora Plus', 'both', 'C', '4', '4', 't', '3', '{gut,probiotic,tcvm}', 'DVM/TCVM-founded brand; NASC Quality Seal; ambassador page currently offline.', 'Herbsmith', 'https://herbsmithinc.com', 'Ambassador (page 404 as of 2026-09-07)', 'https://www.herbsmithinc.com/ambassador/', 'unverified', 't', 'Program status unverified', 'brand_claim'),
  ('honestpaws_mobility_cbd', 'supplements', 'Honest Paws Mobility CBD Oil', 'both', 'B', '4', '4', 't', '4', '{joint,mobility,cbd}', 'USDA-organic hemp CBD for joint comfort; third-party lab tested.', 'Honest Paws', 'https://www.honestpaws.com', 'ShareASale', 'https://www.honestpaws.com/pages/affiliates', 'up to 25%, 30-day cookie', 't', 'Brand affiliate page', 'brand_claim'),
  ('honestpaws_probiotics', 'probiotics', 'Honest Paws Pre+Probiotics', 'dog', 'C', '4', '4', 't', '4', '{gut,probiotic}', 'Multi-strain probiotic with prebiotic fiber; NASC Quality Seal.', 'Honest Paws', 'https://www.honestpaws.com', 'ShareASale', 'https://www.honestpaws.com/pages/affiliates', 'up to 25%, 30-day cookie', 't', 'Brand affiliate page', 'brand_claim'),
  ('mercola_complete_probiotics', 'probiotics', 'Bark & Whiskers Complete Probiotics', 'both', 'C', '3', '4', 'f', '3', '{gut,probiotic}', 'Formerly Dr. Mercola Healthy Pets; NASC member without seal.', 'Bark & Whiskers (Mercola Market)', 'https://www.mercolamarket.com/pages/bark-whiskers', 'FirstPromoter', 'https://www.mercolamarket.com/pages/become-an-affiliate', '10%', 'f', 'Brand affiliate page', 'brand_claim'),
  ('nativepet_the_daily', 'supplements', 'Native Pet The Daily', 'dog', 'C', '5', '5', 't', '3', '{multivitamin,daily,clean-label}', 'Formulated by a DACVIM (Nutrition) veterinarian; NASC Quality Seal.', 'Native Pet', 'https://nativepet.com', 'Awin / FlexOffers', 'https://ui.awin.com/merchant-profile-terms/93325/ppc', '1.6% (FlexOffers); Awin rate not published, 30-day cookie', 't', 'Network listings', 'brand_claim'),
  ('nordic_omega3_pet', 'omega3', 'Nordic Naturals Omega-3 Pet', 'both', 'B', '5', '5', 't', '5', '{skin,coat,joint,omega-3}', 'Lot-tested fish oil with published COAs; NASC Quality Seal; vet professional program.', 'Nordic Naturals', 'https://www.nordic.com/nordic-pet/', 'Rakuten (listing unverified); Pro Nordic Pet vet accounts', 'https://vet.nordicnaturals.com/', 'not published', 't', 'COAs published on brand site', 'brand_claim'),
  ('nutramax_denamarin', 'supplements', 'Nutramax Denamarin', 'both', 'B', '4', '4', 't', '5', '{hepatic,liver,same,silybin}', 'SAMe + silybin liver support widely prescribed by vets.', 'Nutramax Laboratories', 'https://www.nutramaxlabs.com', 'none (retailer programs only)', '', 'n/a', 'f', 'Not NASC-listed', 'brand_claim'),
  ('nutramax_proviable', 'probiotics', 'Nutramax Proviable-DC', 'both', 'B', '4', '4', 't', '5', '{gut,probiotic,vet-recommended}', 'Multi-strain vet-channel probiotic; no brand affiliate (retailer programs only).', 'Nutramax Laboratories', 'https://www.nutramaxlabs.com', 'none (Chewy/Amazon retailer programs only)', '', 'n/a', 'f', 'Not NASC-listed; in-house research program', 'brand_claim'),
  ('onlynaturalpet_hip_joint', 'supplements', 'Only Natural Pet Hip & Joint', 'both', 'C', '4', '4', 't', '3', '{joint,mobility}', 'B Corp retailer own-brand joint support; NASC Quality Seal.', 'Only Natural Pet', 'https://www.onlynaturalpet.com', 'CJ / ShareASale / Rakuten (Versa Marketing)', 'https://www.versamarketinginc.com/only-natural-pet-affiliate-program/', '8%+ (higher on own-brand), 45-day cookie', 't', 'Program page (Versa Marketing)', 'brand_claim'),
  ('petdomain_arthroplex', 'supplements', 'PetDomain Arthroplex', 'both', 'B', '5', '5', 't', '4', '{joint,mobility,senior}', 'Glucosamine/GLM/curcumin joint formula used by 1,000+ vet practices.', 'PetDomain (ex-ThorneVet)', 'https://petdomain.com', 'Vet Portal / Vet Express', 'https://petdomain.com/vet-portal/', 'not published', 't', 'Practitioner channel', 'brand_claim'),
  ('petdomain_curcuvet', 'supplements', 'PetDomain CurcuVET-SA150 (formerly ThorneVet)', 'both', 'B', '5', '5', 't', '4', '{joint,inflammation,curcumin}', 'Practitioner-grade curcumin phytosome; NASC founding member; third-party tested.', 'PetDomain (ex-ThorneVet)', 'https://petdomain.com', 'Vet Portal / Vet Express (practitioner links; no consumer affiliate)', 'https://petdomain.com/vet-portal/', 'not published', 't', 'ThorneVet rebranded to PetDomain', 'brand_claim'),
  ('pethonesty_10in1', 'supplements', 'Pet Honesty 10-in-1 Multivitamin', 'dog', 'C', '4', '4', 't', '4', '{multivitamin,daily}', 'Daily multivitamin soft chew; NASC Quality Seal.', 'Pet Honesty', 'https://www.pethonesty.com', 'Superfiliate (creator) / Pepperjam-Ascend', 'https://www.pethonesty.com/pages/creator-affiliateprogram', 'from 15% (creator code); 8–20%, 7-day cookie (network)', 't', 'Brand creator page; network rate third-party', 'brand_claim'),
  ('pettides_head_to_tail_bpc157', 'supplements', 'PetTides Head to Tail (BPC-157)', 'both', 'D', '3', '3', 't', '2', '{gut,tissue-repair,peptide,regulatory-grey}', 'Oral BPC-157 capsules for pets; regulatory grey area, not NASC-listed.', 'Integrative Peptides / PetTides', 'https://pettides.com', 'In-house affiliate (Integrative Peptides)', 'https://integrativepeptides.com/affiliate-program-registration/', '10%; pet-site inclusion unverified', 'f', 'Third-party testing claimed; no COAs shown', 'crowdsourced_unverified'),
  ('petwellbeing_kidney_support_gold', 'supplements', 'Kidney Support Gold', 'both', 'C', '5', '4', 't', '4', '{renal,senior,herbal}', 'Vet-formulated herbal kidney support; NASC Quality Seal, third-party tested.', 'Pet Wellbeing', 'https://petwellbeing.com', 'Awin (Affiliate & Practitioner Program)', 'https://petwellbeing.com/pages/affiliate-program', '10%, 60-day cookie', 't', 'NASC member list 2026-09-07; brand affiliate page', 'brand_claim'),
  ('petwellbeing_milk_thistle', 'supplements', 'Milk Thistle for Dogs & Cats', 'both', 'C', '5', '4', 't', '4', '{hepatic,liver,herbal}', 'Liquid milk-thistle liver support; NASC Quality Seal.', 'Pet Wellbeing', 'https://petwellbeing.com', 'Awin (Affiliate & Practitioner Program)', 'https://petwellbeing.com/pages/affiliate-program', '10%, 60-day cookie', 't', 'Brand affiliate page', 'brand_claim'),
  ('realmushrooms_5defenders_pets', 'supplements', '5 Defenders for Pets', 'both', 'C', '5', '5', 't', '3', '{immune,mushroom}', 'Five-mushroom immune blend for pets; third-party tested.', 'Real Mushrooms', 'https://realmushrooms.com', 'Social Snowball (in-house)', 'https://www.realmushrooms.com/affiliate-program/', '15%, 30-day cookie', 't', 'Brand affiliate page', 'brand_claim'),
  ('realmushrooms_turkey_tail_pets', 'supplements', 'Turkey Tail for Pets', 'both', 'B', '5', '5', 't', '4', '{immune,cancer-support,mushroom}', '100% fruiting-body turkey tail, DVM-formulated, identity + contaminant tested; NASC Quality Seal.', 'Real Mushrooms', 'https://realmushrooms.com/products/turkey-tail-extract-capsules-for-pets', 'Social Snowball (in-house)', 'https://www.realmushrooms.com/affiliate-program/', '15%, 30-day cookie', 't', 'Brand affiliate page; pet SKUs included', 'brand_claim'),
  ('standardprocess_canine_enteric', 'supplements', 'Standard Process Canine Enteric Support', 'dog', 'C', '4', '4', 'f', '4', '{gut,whole-food,practitioner-only}', 'Whole-food GI support; vet-gated via Patient Direct code.', 'Standard Process Veterinary Formulas', 'https://www.standardprocess.com/brands/veterinary-supplements', 'Patient Direct (practitioner code; no affiliate)', 'https://www.standardprocess.com/apply', 'n/a', 'f', 'NASC member without seal; no public COAs', 'brand_claim'),
  ('standardprocess_feline_renal', 'supplements', 'Standard Process Feline Renal Support', 'cat', 'C', '4', '4', 'f', '4', '{renal,whole-food,practitioner-only}', 'Whole-food kidney support; vet-gated via Patient Direct code.', 'Standard Process Veterinary Formulas', 'https://www.standardprocess.com/brands/veterinary-supplements', 'Patient Direct (practitioner code; no affiliate)', 'https://www.standardprocess.com/apply', 'n/a', 'f', 'NASC member without seal', 'brand_claim'),
  ('vetriscience_composure', 'supplements', 'VetriScience Composure', 'both', 'B', '5', '4', 't', '4', '{calming,anxiety,colostrum,l-theanine}', 'Colostrum calming complex + L-theanine; NASC Quality Seal.', 'VetriScience', 'https://www.vetriscience.com', 'VetriSquad ambassador → affiliate', 'https://about.vetriscience.com/join-the-vetrisquad', 'not published', 't', 'Ambassador program page', 'brand_claim'),
  ('vetriscience_glycoflex', 'supplements', 'VetriScience GlycoFlex 3', 'both', 'B', '5', '4', 't', '5', '{joint,mobility,glm}', 'GLM + glucosamine joint chew; SQF facility; NASC Quality Seal.', 'VetriScience', 'https://www.vetriscience.com', 'VetriSquad ambassador → affiliate', 'https://about.vetriscience.com/join-the-vetrisquad', 'not published', 't', 'Ambassador program page', 'brand_claim'),
  ('wizard_vortex_rx', 'supplements', 'Wizard Sciences Vortex Rx for Dogs & Cats', 'both', 'D', '2', '3', 'f', '2', '{joint,antioxidant,c60}', 'C60 lipofullerene + astaxanthin blend; no testing certificates or NASC listing.', 'Wizard Sciences', 'https://wizardsciences.com/products/vortex-rx-for-dogs-cats', 'none found', '', 'n/a', 'f', 'Single pet SKU; no affiliate program', 'crowdsourced_unverified'),
  ('zestypaws_probiotic_bites', 'probiotics', 'Zesty Paws Probiotic Bites', 'both', 'C', '4', '3', 't', '4', '{gut,probiotic,mass-market}', 'Mass-market chews with NASC Quality Seal; low network commission.', 'Zesty Paws', 'https://www.zestypaws.com', 'Rakuten / FlexOffers', 'https://www.flexoffers.com/affiliate-programs/zesty-paws-affiliate-program/', '3–4%, 30-day cookie (directories)', 't', 'Rates third-party reported', 'brand_claim')
on conflict (slug) do nothing;
