-- 0030_standard_process_line_seed.sql
-- Full Standard Process Veterinary Formulas line (from the 2026-09-07 brand
-- research; flagship SKUs confirmed via brand/reseller/press pages). Added
-- because the app owner holds a Standard Process practitioner account, making
-- Patient Direct the live purchase path for these products.
--
-- Scores mirror the two SP rows seeded in 0028: strong clinical/manufacturing
-- credibility (own organic farm, vet-channel distribution) but NASC member
-- WITHOUT the Quality Seal and no public COAs — so lab_tested stays false and
-- evidence stays C. Rankings are never adjusted for the owner's affiliate or
-- practitioner relationships (see AFFILIATE_DISCLOSURE in the app).
--
-- affiliate_url is the Patient Direct registration page; the owner's 6-digit
-- practitioner code is surfaced separately once provided (source_notes).
insert into public.marketplace_products (slug, category, name, species, evidence, transparency, ingredient_quality, lab_tested, reported_outcomes, fit_tags, blurb, brand, product_url, affiliate_program, affiliate_url, affiliate_commission, nasc_seal, source_notes, evidence_status) values
  ('standardprocess_canine_msk', 'supplements', 'Standard Process Canine Musculoskeletal Support', 'dog', 'C', 4, 4, false, 4, '{joint,mobility,whole-food,practitioner-only}', 'Whole-food joint and muscle support; vet-gated via Patient Direct.', 'Standard Process Veterinary Formulas', 'https://www.standardprocess.com/products/canine-musculoskeletal-support', 'Patient Direct (practitioner code)', 'https://my.standardprocess.com/Patient-Direct', 'practitioner channel', false, 'NASC member without seal; no public COAs', 'brand_claim'),
  ('standardprocess_feline_enteric', 'supplements', 'Standard Process Feline Enteric Support', 'cat', 'C', 4, 4, false, 4, '{gut,whole-food,practitioner-only}', 'Whole-food GI support for cats; vet-gated via Patient Direct.', 'Standard Process Veterinary Formulas', 'https://www.standardprocess.com/brands/veterinary-supplements', 'Patient Direct (practitioner code)', 'https://my.standardprocess.com/Patient-Direct', 'practitioner channel', false, 'NASC member without seal', 'brand_claim'),
  ('standardprocess_canine_renal', 'supplements', 'Standard Process Canine Renal Support', 'dog', 'C', 4, 4, false, 4, '{renal,whole-food,practitioner-only}', 'Whole-food kidney support for dogs; vet-gated via Patient Direct.', 'Standard Process Veterinary Formulas', 'https://www.standardprocess.com/brands/veterinary-supplements', 'Patient Direct (practitioner code)', 'https://my.standardprocess.com/Patient-Direct', 'practitioner channel', false, 'NASC member without seal', 'brand_claim'),
  ('standardprocess_canine_hepatic', 'supplements', 'Standard Process Canine Hepatic Support', 'dog', 'C', 4, 4, false, 4, '{hepatic,liver,whole-food,practitioner-only}', 'Whole-food liver support for dogs; vet-gated via Patient Direct.', 'Standard Process Veterinary Formulas', 'https://www.standardprocess.com/brands/veterinary-supplements', 'Patient Direct (practitioner code)', 'https://my.standardprocess.com/Patient-Direct', 'practitioner channel', false, 'NASC member without seal', 'brand_claim'),
  ('standardprocess_feline_hepatic', 'supplements', 'Standard Process Feline Hepatic Support', 'cat', 'C', 4, 4, false, 4, '{hepatic,liver,whole-food,practitioner-only}', 'Whole-food liver support for cats; vet-gated via Patient Direct.', 'Standard Process Veterinary Formulas', 'https://www.standardprocess.com/brands/veterinary-supplements', 'Patient Direct (practitioner code)', 'https://my.standardprocess.com/Patient-Direct', 'practitioner channel', false, 'NASC member without seal', 'brand_claim'),
  ('standardprocess_canine_whole_body', 'supplements', 'Standard Process Canine Whole Body Support', 'dog', 'C', 4, 4, false, 4, '{multivitamin,daily,whole-food,practitioner-only}', 'Whole-food daily foundation formula for dogs.', 'Standard Process Veterinary Formulas', 'https://www.standardprocess.com/brands/veterinary-supplements', 'Patient Direct (practitioner code)', 'https://my.standardprocess.com/Patient-Direct', 'practitioner channel', false, 'NASC member without seal', 'brand_claim'),
  ('standardprocess_feline_whole_body', 'supplements', 'Standard Process Feline Whole Body Support', 'cat', 'C', 4, 4, false, 4, '{multivitamin,daily,whole-food,practitioner-only}', 'Whole-food daily foundation formula for cats.', 'Standard Process Veterinary Formulas', 'https://www.standardprocess.com/brands/veterinary-supplements', 'Patient Direct (practitioner code)', 'https://my.standardprocess.com/Patient-Direct', 'practitioner channel', false, 'NASC member without seal', 'brand_claim'),
  ('standardprocess_canine_cognition', 'supplements', 'Standard Process Canine Cognition Support', 'dog', 'C', 4, 4, false, 3, '{cognitive,senior,whole-food,practitioner-only}', 'Senior cognitive support launched 2026; available exclusively through veterinary practices.', 'Standard Process Veterinary Formulas', 'https://www.standardprocess.com/brands/veterinary-supplements', 'Patient Direct (practitioner code)', 'https://my.standardprocess.com/Patient-Direct', 'practitioner channel', false, 'Launched 2026-03; NASC member without seal', 'brand_claim'),
  ('standardprocess_feline_immune', 'supplements', 'Standard Process Feline Immune System Support', 'cat', 'C', 4, 4, false, 4, '{immune,whole-food,practitioner-only}', 'Whole-food immune support for cats; vet-gated via Patient Direct.', 'Standard Process Veterinary Formulas', 'https://www.standardprocess.com/brands/veterinary-supplements', 'Patient Direct (practitioner code)', 'https://my.standardprocess.com/Patient-Direct', 'practitioner channel', false, 'NASC member without seal', 'brand_claim'),
  ('standardprocess_vf_omega3', 'omega3', 'Standard Process VF Omega-3 for Pets', 'both', 'C', 4, 4, false, 4, '{skin,coat,joint,omega-3,practitioner-only}', 'Practitioner-channel omega-3 for dogs and cats.', 'Standard Process Veterinary Formulas', 'https://www.standardprocess.com/brands/veterinary-supplements', 'Patient Direct (practitioner code)', 'https://my.standardprocess.com/Patient-Direct', 'practitioner channel', false, 'NASC member without seal; no public COAs', 'brand_claim')
on conflict (slug) do nothing;
